// const crud = ['addnew', 'insert', 'update', 'delete']
module.exports = [
  {
    name: 'acc_editorOrderCompetitionAll',
    description: 'Відповідальний за добір персоналу',
    description_uk: 'Відповідальний за добір персоналу',
    description_ru: 'Ответственный за подбор персонала',
    sessionTimeout: 30,
    allowedAppMethods: 'changePassword,checkDocument,getDocument,getDomainInfo,logout,rest,setDocument,ubql',
    desktopsCodes: ['arm_accHREmpAdd', 'arm_accStaff'],
    shortcutCodes: [
      'accHREmpAdd_competitionFolder',
      'accHREmpAddFolderDictionary',
      'accHREmpAdd_adCompetition',
      'hr_empOrderAdCompetitionA',
      'accHREmpAddRequestForStuff',
      'hr_requestForStuff',
      'accHREmpRequestStuffMotion',
      'hr_requestStuffMotion',
      'accHREmpAdd_empListAudit',
      'hr_empListAudit',
      'accHREmpAdd_dictCompetency',
      'hr_dictCompetency',
      'accHREmpAdd_dictBasicFunctn',
      'hr_dictBasicFunctn',
      'accHREmpAdd_dictAreasActivity',
      'hr_dictAreasActivity',
      'accHREmpAdd_dictRequiredPosition',
      'hr_dictRequiredPosition',
      'accHREmpAdd_dictRequiredPara',
      'hr_dictRequiredPara',
      'accHREmpAdd_CompetitionReport',
      'accHREmpAdd_hr_listPosContestOrg',
      'hr_listPosContestOrg',
      'accHREmpAdd_hr_listPosContestPubA',
      'hr_listPosContestPubA',
      'reportsHREmpAdd',
      'hr_vacanciesCompetitionList',
      'accHREmpAdd_listPosContest',
      'hr_listPosContestWin',
      'accHREmpAdd_positionInstructionList',
      'hr_positionInstructionList',
      'accStaff_position',
      'hr_position',
      'accStaff_dictNameAddition',
      'hr_dictNameAddition',
      'hr_dictEventKnowledg'
    ],
    elsRule: [
      { description: 'Наказ з персоналу',
        entityMask: 'hr_empOrder',
        methodMask: [
          'repPrintForm',
          'select',
          'addnew',
          'insert',
          'update',
          'delete',
          'doPosting',
          'saveReportSettings',
          'fillOrderAccrual',
          'fillOrderAccrualWithSave',
          'getWorkDays',
          'getWorkDays4Vac',
          'setDateAndNumber',
          'docPrintForm',
          'isWorkDay',
          'getValidatorWarning',
          'fillOrderExperience',
          'clearOrder*',
          'doPosting_COMPETITIONAD',
          'exchangeReview',
          'sendReview',
          'addStampData', 'getDocumentWithStampData'
        ]
      },
      { description: 'Індекс номеру наказу', entityMask: 'hr_dictEmpOrderIndex', methodMask: ['*'] },
      { description: 'Заявка на добір персоналу', entityMask: 'hr_requestForStuff', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Заявка на добір персоналу. Освіта', entityMask: 'hr_requestStuffEducation', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Заявка на добір персоналу. Досвід роботи', entityMask: 'hr_requestStuffExperience', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Заявка на добір персоналу. Професійні знання', entityMask: 'hr_requestStuffProfi', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Заявка на добір персоналу. Комп\'ютерна грамотність', entityMask: 'hr_requestStuffPcLiteracy', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Заявка на добір персоналу. Ділові якості', entityMask: 'hr_requestStuffComp', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Заявка на добір персоналу. Особисті якості', entityMask: 'hr_requestStuffPrivat', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Подання щодо добору персоналу', entityMask: 'hr_requestStuffMotion', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Експерти', entityMask: 'hr_requestStuffExpert', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Журнал перевірок', entityMask: 'hr_empListAudit', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'search'] },
      { description: 'Компетенції', entityMask: 'hr_dictCompetency', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Основні функції організацій та підрозділів', entityMask: 'hr_dictBasicFunctn', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Напрями діяльності', entityMask: 'hr_dictAreasActivity', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Вимоги до посади', entityMask: 'hr_dictRequiredPosition', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Пункти вимоги', entityMask: 'hr_dictRequiredPara', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Реєстр конкурсних посад', entityMask: 'hr_listPosContest', methodMask: ['select'] },
      { description: 'Участник согласования документа', entityMask: 'hr_recparticipant', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_export', entityMask: 'hr_export', methodMask: ['exportPublicData', 'getJsonFile', 'exportPosContest', 'setPosContestResult', 'uploadPublicData'] },
      { description: 'hr_empOrderCompetitionadDet', entityMask: 'hr_empOrderCompetitionadDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_empOrderCompetitionadPosDet', entityMask: 'hr_empOrderCompetitionadPosDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_empOrderAppointDet', entityMask: 'hr_empOrderAppointDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_empOrderTaskDet', entityMask: 'hr_empOrderTaskDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_listPosContestDet', entityMask: 'hr_listPosContestDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionInstruction', entityMask: 'hr_positionInstruction', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'repPrintForm'] },
      { description: 'hr_positionMainResponsibiliti', entityMask: 'hr_positionMainResponsibiliti', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'loadPositionRespons'] },
      { description: 'hr_positionRightResponsibiliti', entityMask: 'hr_positionRightResponsibiliti', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionServiceCommunication', entityMask: 'hr_positionServiceCommunication', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionSpecReq', entityMask: 'hr_positionSpecReq', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionEducation', entityMask: 'hr_positionEducation', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionExperience', entityMask: 'hr_positionExperience', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionProfi', entityMask: 'hr_positionProfi', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_positionPcLiteracy', entityMask: 'hr_positionPcLiteracy', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_position', entityMask: 'hr_position', methodMask: ['select', 'update', 'getSupervisorPosition', 'calcFunds', 'getPlanSumByPosition'] },
      { description: 'hr_positionInstructionAcqList', entityMask: 'hr_positionInstructionAcqList', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Посадовий обов\'язок', entityMask: 'hr_positionResp', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Кваліфікаційна вимога', entityMask: 'hr_positionQualif', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Вид шкідливих умов праці', entityMask: 'hr_positionHarmful', methodMask: ['select'] },
      { description: 'hr_staffUnitAttachment', entityMask: 'hr_staffUnitAttachment', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_employeeNumber', entityMask: 'hr_employeeNumber', methodMask: ['select', 'getNextTabNum'] },
      { description: 'hr_empOrderFundSource', entityMask: 'hr_empOrderFundSource', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'getPosFundSourceData', 'getOrderFundSourceData'] },
      {
        description: 'hr_employeeNumberS',
        entityMask: 'hr_employeeNumberS',
        methodMask: [ 'select' ]
      },
      {
        description: 'hr_employeeNumberSR',
        entityMask: 'hr_employeeNumberSR',
        methodMask: [ 'select' ]
      },
      { description: 'hr_empOrderExperience', entityMask: 'hr_empOrderExperience', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'hr_empOrderAcc', entityMask: 'hr_empOrderAcc', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'replaceDateFrom', 'fillOrderAccrual', 'clearOrderAccrual'] },
      { description: 'hr_employee', entityMask: 'hr_employee', methodMask: ['getNextPublServRang'] },
      {
        description: 'Этап согласования',
        entityMask: 'hr_recstage',
        methodMask: [ 'select', 'addnew', 'insert', 'update', 'delete', 'startReconciliation', 'stopReconciliation',
          'continueReconciliation', 'cancelReconciliation',
          'canVisibleStartReconciliation', 'canVisibleStopReconciliation',
          'canVisibleContinueReconciliation', 'canVisibleCancelReconciliation']
      },
      {
        description: 'Лист ознайомлення',
        entityMask: 'hr_acquaintanceList',
        methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'addEvaluationType']
      },
      {
        description: 'hr_orderAttachment',
        entityMask: 'hr_orderAttachment',
        methodMask: ['select', 'addnew', 'insert', 'update', 'delete']
      },
      {
        description: 'hr_employeePosition',
        entityMask: 'hr_employeePosition',
        methodMask: ['getOrderSignerInfo', 'getOrderSignerList']
      },
      {
        description: 'hr_employeePositionS',
        entityMask: 'hr_employeePositionS',
        methodMask: ['getTempExecution']
      },
      {
        description: 'Доповнення до назви',
        entityMask: 'hr_dictNameAddition',
        methodMask: ['select', 'addnew', 'insert', 'update', 'delete']
      },
      {
        description: 'ac_service',
        entityMask: 'ac_service',
        methodMask: ['userIsMemberOf']
      },
      { description: 'Лист розсилки', entityMask: 'hr_mailingLetter', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Шаблон листа розсилки', entityMask: 'hr_mailingLetterTemplate', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'loadFromTemplate'] },
      { description: 'Шаблон листа розсилки. Учасники', entityMask: 'hr_mailingLetterTemplateDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Лист підписантів', entityMask: 'hr_empOrderSignDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Шаблон листа підписантів', entityMask: 'hr_empOrderSignTemplate', methodMask: ['*'] },
      { description: 'Шаблон листа підписантів. Учасники', entityMask: 'hr_empOrderSignTemplateDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
      { description: 'Лист погодження', entityMask: 'hr_empOrdListAppruv', methodMask: ['*'] },
      { description: 'Шаблон листа погодження', entityMask: 'hr_empOrdListAppruvTemplate', methodMask: ['*'] },
      { description: 'Шаблон листа погодження. Учасники', entityMask: 'hr_empOrdListAppruvTemplateDt', methodMask: ['*'] },
      { description: 'Шаблон листа ознайомлення', entityMask: 'hr_empOrderAcquaintListTpl', methodMask: ['*'] },
      { description: 'Шаблон листа ознайомлення. Учасники', entityMask: 'hr_empOrderAcquaintListTplDet', methodMask: ['*'] },
      { description: 'Події ознайомлення', entityMask: 'hr_dictEventKnowledg', methodMask: [ '*' ] },
      {
        description: 'hr_employeeNumberS',
        entityMask: 'hr_employeeNumberS',
        methodMask: [ 'select' ]
      },
      {
        description: 'hr_orderStateHistory',
        entityMask: 'hr_orderStateHistory',
        methodMask: [ 'select' ]
      },
      {
        description: 'hr_empOrdListAppruv',
        entityMask: 'hr_empOrdListAppruv',
        methodMask: ['*']
      }
    ]
  }
]
