module.exports = [{
  name: 'acc_mainEconomicWork',
  description: 'Відповідальний за накази з планово-економічної роботи',
  description_uk: 'Відповідальний за накази з планово-економічної роботи',
  description_ru: 'Ответственный за приказы по планово-экономической работе',
  description_az: 'Planlaşdırma və iqtisadi işlər üzrə sifarişlərə cavabdehdir',
  sessionTimeout: 30,
  allowedAppMethods: 'changePassword,checkDocument,getDocument,getDomainInfo,logout,rest,setDocument,ubql',
  desktopsCodes: ['arm_accHR', 'arm_accStaff'],
  shortcutCodes: [
    'accHR_empOrderChgsalaryA',
    'hr_empOrderChgsalaryA',
    'accStaffFolderOrder',
    'accHR_empOrderStaffTableMove',
    'hr_empOrderStaffTableMove',
    'accHRFolderOrdersChgSalary',
    'hr_empOrderAddSalaryA',
    'accHR_empOrderAddSalaryA',
    'accHR_empOrderBountyA',
    'hr_empOrderBountyA',
    'accHR_empOrderBountyHelpA',
    'hr_empOrderBountyHelpA',
    'accHR_empOrderAddSalaryGovA',
    'hr_empOrderAddSalaryGovA',
    'accHR_empOrderRiskPayA',
    'hr_empOrderRiskPayA',
    'accHR_empOrderAddPayA',
    'hr_empOrderAddPayA'
  ],
  elsRule: [
    { description: 'hr_empOrder', entityMask: 'hr_empOrder', methodMask: ['select'] },
    {
      description: 'Наказ з персоналу',
      entityMask: 'hr_empOrder*',
      methodMask: ['select', 'addnew', 'insert',
        'update', 'delete', 'checkTabNum', 'clearDetail', 'saveReportSettings', 'fillOrderAccrual', 'getWorkDays',
        'getCalendDays4Vac', 'getWorkDays4Vac', 'getCalendDateTo4Vac', 'getWorkDateTo4Vac', 'setDateAndNumber', 'docPrintForm',
        'repPrintForm', 'isWorkDay', 'setItemIdx', 'moveItemUp', 'moveItemDown', 'enumerateItems', 'checkYearMissionDays',
        'getYearInfo', 'getDescriptionExt', 'getActiveVacationList', 'cloneVacationList', 'recalcBounty', 'fillEmployee', 'addPeriods',
        'loadEmployeeList', 'createOrder', 'addList', 'getValidatorWarning', 'updateOrderFieldLastChangeDate', 'fillOrderExperience',
        'clearOrder*', 'search', 'checkCrossTimeSheet', 'closeDateTo', 'checkRankInYear', 'updateBountyPayEl',
        'fillOrderAccrualWithSave', 'calcVacationMoveList', 'clearActingDet', 'fillVacSubstitution', 'clearVacSubstitutionDet',
        'vacSubstitutionNote', 'checkVacSubstitution', 'validateVacSubstitution', 'canEditOrdersMainOrg', 'clearDetail', 'loadEmployeeList',
        'doPosting', 'doCancelPosting', 'doPosting_CHGSALARY', 'doCancelPosting_CHGSALARY', 'doPosting_STAFFTABLEMOVE',
        'doCancelPosting_STAFFTABLEMOVE', 'doPosting_ADDSALARY', 'doCancelPosting_ADDSALARY', 'doPosting_ADDPAY', 'doCancelPosting_ADDPAY',
        'doPosting_RISKPAY', 'doCancelPosting_RISKPAY', 'doPosting_ADDSALARYGOV', 'doCancelPosting_ADDSALARYGOV',
        'doPosting_BOUNTY_HELP', 'doCancelPosting_BOUNTY_HELP', 'doPosting_BOUNTY', 'doCancelPosting_BOUNTY',
        'getVacListIDs', 'addStampData', 'getDocumentWithStampData'
      ]
    },
    { description: 'Додатки до наказів', entityMask: 'hr_orderAttachment', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
    { description: 'Лист ознайомлення', entityMask: 'hr_acquaintanceList', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'addEvaluationType'] },
    { description: 'hr_empOrderFundSource', entityMask: 'hr_empOrderFundSource', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
    {
      description: 'Этап согласования',
      entityMask: 'hr_recstage',
      methodMask: ['select', 'addnew', 'insert', 'update', 'delete',
        'startReconciliation', 'stopReconciliation', 'continueReconciliation', 'cancelReconciliation', 'canVisibleStartReconciliation',
        'canVisibleStopReconciliation', 'canVisibleContinueReconciliation', 'canVisibleCancelReconciliation']
    },
    { description: 'Участник согласования', entityMask: 'hr_recparticipant', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
    { description: 'Особа', entityMask: 'hr_employee', methodMask: ['getNextPublServRang'] },
    { description: 'Посада', entityMask: 'hr_position', methodMask: ['select', 'calcFunds', 'getPlanSumByPosition'] },
    { description: 'Заголовок та преамбула', entityMask: 'hr_dictEmpOrderText', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
    {
      description: 'Наказ про встановлення посадових окладів. Працівники',
      entityMask: 'hr_empOrderChgSalEmpDet',
      methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'fillAddSalary', 'fillCancelSalary']
    },
    { description: 'Шаблон узгодження', entityMask: 'hr_recstageTemplate', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'loadFromTemplate'] },
    { description: 'Призначення працівника', entityMask: 'hr_employeePosition', methodMask: ['select', 'getOrderSignerInfo', 'getOrderSignerList'] },
    { description: 'Призначення працівника', entityMask: 'hr_employeePositionS', methodMask: ['select', 'getTempExecution', 'selectPosGroups'] },
    { description: 'Покладання обов\'язків', entityMask: 'hr_empOrderActingDet', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'clearDetail', 'closeDateTo'] },
    { description: 'Наказ про встановлення надбавок', entityMask: 'hr_empOrderAddsalaryDet', methodMask: ['clearEmployees', 'loadAccrualChangesFromStaffTable', 'loadAccrualChangesFromStaffTariffing'] },
    { description: 'Наказ про встановлення надбавок за вислугу років', entityMask: 'hr_empOrderAddsalarygovDet', methodMask: ['checkAccrualDates'] },
    { description: 'Підстави для передачі мат. цінностей', entityMask: 'hr_dictReasonMaterialtransfer', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
    { description: 'hr_staffTable', entityMask: 'hr_staffTable', methodMask: ['getStaffTableMoveEmployees'] },
    { description: 'Виконуючі обов\'язки', entityMask: 'hr_empActingList', methodMask: ['closeDateTo'] },
    { description: 'Підстава наказу', entityMask: 'hr_dictOrderDetReason', methodMask: ['select', 'addnew', 'insert', 'update', 'delete'] },
    { description: 'hr_staffTariffing', entityMask: 'hr_staffTariffing', methodMask: ['getStaffTariffingMoveEmployees'] },
    { description: 'Нарахування до пункту наказу', entityMask: 'hr_empOrderAcc', methodMask: ['select', 'addnew', 'insert', 'update', 'delete', 'replaceDateFrom', 'fillOrderAccrual', 'clearOrderAccrual'] }
  ]
}]
