<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Заява-розрахунок</xs:documentation>
	</xs:annotation>

	<xs:include schemaLocation="common_types.xsd" />

	<xs:element name="DECLAR" type="DeclarContent"/>
	<xs:complexType name="DeclarContent">
		<xs:sequence>
			<xs:element name="DECLARHEAD" type="DHead"/>
			<xs:element name="DECLARBODY" type="DBody"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DHead">
		<xs:sequence>
			<xs:element name="TIN" type="DGLong" minOccurs="1" maxOccurs="1"/>
			<xs:element name="C_DOC" type="xs:string" minOccurs="1" maxOccurs="1" fixed="C11"/>
			<xs:element name="C_DOC_SUB" type="xs:string" minOccurs="1" maxOccurs="1" fixed="001"/>
			<xs:element name="C_DOC_VER" type="xs:string" minOccurs="1" maxOccurs="1" fixed="01"/>
			<xs:element name="C_REG" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PERIOD_MONTH" type="DGMonth" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PERIOD_TYPE" type="DGPType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PERIOD_YEAR" type="DGYear" minOccurs="1" maxOccurs="1"/>
			<xs:element name="C_DOC_STAN" type="DGSTAN" minOccurs="1" maxOccurs="1" />
			<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1" />
			<xs:element name="SOFTWARE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DBody">
		<xs:sequence>
			<!-- Main -->
			<xs:element name="UNICODE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="CST_CAPTION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DATE_FORMATION" type="DGDate"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="CHIEF" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="BOOKKEEPER" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ADDRESS" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="CAPTION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ACCOUNT" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MFO" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TVP_DAYS" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TVP_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MATERNITY_DAYS" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MATERNITY_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FUNERAL_COUNT" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FUNERAL_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ACCEDENT_DAYS" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ACCEDENT_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SIMPLIFIED_DAYS" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SIMPLIFIED_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="GRAVE_COUNT" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="GRAVE_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SUM_ALL" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TVP_CHAES_DAYS" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TVP_CHAES_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MATERNITY_CHAES_DAYS" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MATERNITY_CHAES_SUM" type="DGdecimal2"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D1_POSITION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D1_PERSON" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D1_PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D2_POSITION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D2_PERSON" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D2_PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D3_POSITION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D3_PERSON" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D3_PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D4_POSITION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D4_PERSON" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D4_PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D5_POSITION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D5_PERSON" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="D5_PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="N16" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="N17" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="N18" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="N19" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="N20" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="N21" type="xs:integer"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="CSTRAX" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
			<!-- Tab1 -->
			<xs:element name="T1RXXXXG1" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG2S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG3S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG4S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG5S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG6" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG7S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG8S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG9" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG10" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG11D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG12D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG13" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG14" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG15" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG16" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG17" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG18" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG19S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG20D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG21" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG22" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!-- Tab2 -->
			<xs:element name="T2RXXXXG1" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG2S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG3S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG4S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG5S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG6S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG7S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG8S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG9S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG10S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG11" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG12" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!-- Tab3 -->
			<xs:element name="T3RXXXXG1" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG2S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG3S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG4S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG5S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG6" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG7D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG8S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG9S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG10S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG11" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG12D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG13D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG14" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG15" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!-- Tab4 -->
			<xs:element name="T4RXXXXG1" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG2S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG3S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG4S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG5S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG6D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG7S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG8S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG9S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG10" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG11D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG12D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG13" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG14" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!-- Tab5 -->
			<xs:element name="T5RXXXXG1" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG2S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG3S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG4S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG5S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG6D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG7S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG8S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG9S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG10" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
