<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>Повідомлення про виплату коштів застрахованим особам</xs:documentation>
    </xs:annotation>

    <xs:include schemaLocation="common_types.xsd" />

    <xs:element name="DECLAR" type="DeclarContent"/>
    <xs:complexType name="DeclarContent">
        <xs:sequence>
            <xs:element name="DECLARHEAD" type="DHead"/>
            <xs:element name="DECLARBODY" type="DBody"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DHead">
        <xs:sequence>
            <xs:element name="TIN" type="DGLong" minOccurs="1" maxOccurs="1"/>
            <xs:element name="C_DOC" type="xs:string" minOccurs="1" maxOccurs="1" fixed="C11"/>
            <xs:element name="C_DOC_SUB" type="xs:string" minOccurs="1" maxOccurs="1" fixed="002"/>
            <xs:element name="C_DOC_VER" type="xs:string" minOccurs="1" maxOccurs="1" fixed="01"/>
            <xs:element name="C_REG" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="PERIOD_MONTH" type="DGMonth" minOccurs="1" maxOccurs="1"/>
            <xs:element name="PERIOD_TYPE" type="DGPType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="PERIOD_YEAR" type="DGYear" minOccurs="1" maxOccurs="1"/>
            <xs:element name="C_DOC_STAN" type="DGSTAN" minOccurs="1" maxOccurs="1" />
            <xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1" />
            <xs:element name="SOFTWARE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DBody">
        <xs:sequence>
            <!-- Main -->
            <xs:element name="UNICODE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="CST_CAPTION" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="DATE_FORMATION" type="DGDate"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="CHIEF" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="BOOKKEEPER" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="ADDRESS" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="PHONE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <xs:element name="CSTRAX" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
            <!-- Tab1 -->
            <xs:element name="T1RXXXXG1" type="IntColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG2S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG3S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG4S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG5S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG6S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG7S" type="StrColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG8D" type="DateColumn"  nillable="true" minOccurs="0" maxOccurs="9999"/>
            <xs:element name="T1RXXXXG9" type="Decimal2Column"  nillable="true" minOccurs="0" maxOccurs="9999"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
