module.exports = [
  {
    code: 'arm_accSec',
    caption: 'Адміністратор безпеки',
    caption_uk: 'Адміністратор безпеки',
    caption_ru: 'Администратор безопасности',
    caption_az: 'Təhlükəsizlik üzrə administrator',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-user-shield',
    displayOrder: 20,
    description: 'Адміністратор безпеки організації',
    description_uk: 'Адміністратор безпеки організації',
    description_ru: 'Администратор безопасности организации',
    description_az: 'Təşkilatın təhlükəsizlik üzrə administratoru'
  },
  {
    code: 'arm_accHREmpAdd',
    caption: 'Добір персоналу',
    caption_uk: 'Добір персоналу',
    caption_ru: 'Подбор персонала',
    caption_en: 'Recruiting',
    caption_az: 'Vəzifəyə təyinat',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-handshake',
    displayOrder: 80,
    description: 'Добір персоналу',
    description_uk: 'Добір персоналу',
    description_ru: 'Подбор персонала',
    description_en: 'Recruiting',
    description_az: 'İşçi heyətinin əlavə yığımı'
  },
  {
    code: 'arm_accDoc',
    caption: 'Документи',
    caption_uk: 'Документи',
    caption_ru: 'Документы',
    caption_az: 'Sənədlər',
    url: null,
    isDefault: 0,
    iconCls: 'el-icon-document-checked',
    displayOrder: 90,
    description: 'Опрацювання документів',
    description_uk: 'Опрацювання документів',
    description_ru: 'Обработка документов',
    description_az: 'Sənədlərin emalı'
  },
  {
    code: 'arm_accHR',
    caption: 'Накази з Персоналу',
    caption_uk: 'Накази з Персоналу',
    caption_ru: 'Приказы по Персоналу',
    caption_az: 'İşçi heyəti üzrə əmrlər',
    url: null,
    isDefault: 0,
    iconCls: 'el-icon-s-order',
    displayOrder: 150,
    description: 'Накази з Персоналу',
    description_uk: 'Накази з Персоналу',
    description_ru: 'Приказы по Персоналу',
    description_az: 'İşçi heyəti üzrə əmrlər'
  },
  {
    code: 'arm_accFSSU',
    caption: 'Облік документів СС',
    caption_uk: 'Облік документів СС',
    caption_ru: 'Учет документов СС',
    caption_az: 'DSMF sənədlərinin uçotu',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-notes-medical',
    displayOrder: 160,
    description: 'Облік документів СС',
    description_uk: 'Облік документів СС',
    description_ru: 'Учет документов СС',
    description_az: 'SSF-nin sənədlərinin uçotu'
  },
  {
    code: 'arm_accStaff',
    caption: 'Оргструктура',
    caption_uk: 'Оргструктура',
    caption_ru: 'Оргструктура',
    caption_az: 'Təşkilati struktur',
    url: null,
    isDefault: 0,
    iconCls: 'fa fa-cubes',
    displayOrder: 170,
    description: 'Оргструктура',
    description_uk: 'Оргструктура',
    description_ru: 'Оргструктура',
    description_az: 'Təşkilati struktur'
  },
  {
    code: 'arm_accHREmp',
    caption: 'Персонал',
    caption_uk: 'Персонал',
    caption_ru: 'Персонал',
    caption_az: 'İşçi heyəti',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-id-card',
    displayOrder: 190,
    description: 'Персонал',
    description_uk: 'Персонал',
    description_ru: 'Персонал',
    description_az: 'İşçi heyəti'
  },
  {
    code: 'arm_accVacation',
    caption: 'Планування відпусток',
    caption_uk: 'Планування відпусток',
    caption_ru: 'Планирование отпусков',
    caption_az: 'Məzuniyyətin planlaşdırılması',
    url: null,
    isDefault: 0,
    iconCls: 'el-icon-sunrise',
    displayOrder: 200,
    description: 'Планування відпусток',
    description_uk: 'Планування відпусток',
    description_ru: 'Планирование отпусков',
    description_az: 'Məzuniyyətin planlaşdırılması'
  },
  {
    code: 'arm_accHRCarier',
    caption: 'Службова кар’єра',
    caption_uk: 'Службова кар’єра',
    caption_ru: 'Служебная карьера',
    caption_az: 'Xidməti karyera',
    url: null,
    isDefault: 0,
    iconCls: 'el-icon-thumb',
    displayOrder: 220,
    description: 'Службова кар’єра',
    description_uk: 'Службова кар’єра',
    description_ru: 'Служебная карьера',
    description_az: 'Xidməti karyera'
  },
  {
    code: 'arm_accTim',
    caption: 'Табельний облік',
    caption_uk: 'Табельний облік',
    caption_ru: 'Табельный учет',
    caption_az: 'Tabel uçotu',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-hourglass-half',
    displayOrder: 240,
    description: 'Табельний облік',
    description_uk: 'Табельний облік',
    description_ru: 'Табельный учет',
    description_az: 'Tabel uçotu'
  },
  {
    code: 'arm_accDst',
    caption: 'Конфігурація робочих столів',
    caption_uk: 'Конфігурація робочих столів',
    caption_ru: 'Конфигурация рабочих столов',
    caption_az: 'İş masalarının konfiqurasiyası',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-desktop',
    displayOrder: 2020,
    description: 'Конфігурація робочих столів',
    description_uk: 'Конфігурація робочих столів',
    description_ru: 'Конфигурация рабочих столов',
    description_az: 'İş masalarının konfiqurasiyası'
  },
  {
    code: 'arm_accTariffing',
    caption: 'Тарифікація',
    caption_uk: 'Тарифікація',
    caption_ru: 'Тарификация',
    caption_az: 'Tarifləşdirmə',
    url: null,
    isDefault: 0,
    iconCls: 'fas fa-calculator',
    displayOrder: 250,
    description: 'Тарифікація',
    description_uk: 'Тарифікація',
    description_ru: 'Тарификация',
    description_az: 'Tarifikasiya'
  }
]
