module.exports = [
  {
    entity: 'hr_exportFields',
    localeAttr: ['name'],
    identifier: ['type', 'code'],
    attrs: ['code', 'name', 'type', 'tableName', 'tableName1', 'requiredTables'],
    items: [
      [ 'branchCode', 'Код відділення банку', 'filePay', null, null, null ],
      [ 'projectCode', 'Код запрлатного проєкту', 'filePay', null, null, null ],
      [ 'personalAccount', 'Номер рахунку ', 'filePay', null, null, null ],
      [ 'taxCodeType', 'Ідентифікація (ІНН або паспорт)', 'filePay', null, null, null ],
      [ 'fullFIO', 'ПІБ', 'filePay', null, null, null ],
      [ 'lastName', 'Призвище', 'filePay', null, null, null ],
      [ 'firstName', 'Ім"я', 'filePay', null, null, null ],
      [ 'middleName', 'По батькові', 'filePay', null, null, null ],
      [ 'paySum', 'Сума до виплати', 'filePay', null, null, null ],
      [ 'taxCode9', 'Ідентіфікаціонний код (якщо відсутній, то 9 нулів)', 'filePay', null, null, null ],
      [ 'taxCode10', 'Ідентіфікаціонний код (якщо відсутній, то 10  нулів)', 'filePay', null, null, null ],
      [ 'namePayRoll', 'Призначення платежу', 'filePay', null, null, null ],
      [ 'bankSubAccount', 'Номер субрахунку', 'filePay', null, null, null ],
      [ 'tranDate', 'Дата створення відомості', 'filePay', null, null, null ],
      [ 'pNum', 'Порядковий номер співробітника в файлі', 'filePay', null, null, null ],
      [ 'fixValue', 'Фіксоване значення', 'filePay', null, null, null ],
      [ 'balanceCode', 'Балансова одиниця', 'fileSAP', null, null, null ],
      [ 'accountDt', 'Рахунок затрат (Дт)', 'fileSAP', 'gl_account', null,
        JSON.stringify([{ tn: 'gl_account' }])],
      [ 'accountKt', 'Рахунок ЗП (Кт)', 'fileSAP', 'gl_account', null,
        JSON.stringify([{ tn: 'gl_account' }])],
      [ 'payAccOperationSum', 'Сума проведень', 'fileSAP', null, null, null ],
      [ 'mvv', 'МВВ', 'fileSAP', 'ac_dictCostType', null,
        JSON.stringify([{ tn: 'ac_dictCostType' }])],
      [ 'timeSheetHours', 'Відпрацьований час з табеля', 'fileSAP', 'hr_dictTimeCost', null,
        JSON.stringify([{ tn: 'hr_dictTimeCost' }])],
      [ 'tText', 'Опис', 'fileSAP', null, null, null ],
      [ 'tTextDt', 'В описі назва рахунку  Дт', 'fileSAP', null, null, null ],
      [ 'tTextNumber', 'В описі  працівник', 'fileSAP', null, null, null ],
      [ 'tTextPeriodCalc', 'В описі розрахунковий період', 'fileSAP', null, null, null ],
      [ 'orderDate', 'Дата закінчення періода', 'fileSAP', null, null, null ],

      [ 'shortFIO', 'ПІБ працівника (скорочене)', 'fileSAP', null, null, null ],
      [ 'fullFIORecipient', 'ПІБ отримувача (повне)', 'fileSAP', null, null, null ],
      [ 'taxCodeRecipient', 'Ідентіфікатор отримувача', 'fileSAP', null, null, null ],
      [ 'IBANRecipient', 'Номер особового рахунку  отримувача', 'fileSAP', null, null, null ],
      [ 'fullFIORecipientIBAN', 'ПІП отримувача з р/рахунку (повне)', 'fileSAP', null, null, null ],
      [ 'taxCodeRecipientIBAN', 'Ідентифікатор отримувача з р/рахунку', 'fileSAP', null, null, null ],
      [ 'accrualSum', 'Сума з розрахункового листа', 'fileSAP', 'hr_payEl', null,
        JSON.stringify([{ tn: 'hr_payEl' }])],
      [ 'tTextNamePay', 'В описі призначення платежу', 'fileSAP', null, null, null ],
      [ 'tTextFullFIORecipient', 'В описі ПІБ отримувача (повне)', 'fileSAP', null, null, null ],
      [ 'tTextTaxCodeRecipient', 'В описі Ідентіфікатор отримувача', 'fileSAP', null, null, null ],
      [ 'tTextFullFIORecipientIBAN', 'В описі ПІП отримувача з р/рахунку (повне)', 'fileSAP', null, null, null ],
      [ 'tTextTaxCodeRecipientIBAN', 'Ідентифікатор отримувача  з р/рахунку', 'fileSAP', null, null, null ],
      [ 'tTextPayElName', 'Вид оплати', 'fileSAP', null, null, null ],
      [ 'datePayRoll', 'Дата документа на виплату', 'fileSAP', null, null, null ],

      [ 'kodStruct', 'Структурна одиниця', 'fileSAP', null, null, null ],
      [ 'numberMonth', 'Номер місяця', 'fileSAP', null, null, null ],
      [ 'nameMBB', 'Назва МВВ', 'fileSAP', null, null, null ],
      [ 'staffCat', 'Категорія посади', 'fileSAP', null, null, null ],
      [ 'sumAccKtg', 'Сума з розрахункового листа за категоріями посад та МВВ', 'fileSAP',
        'hr_payEl', 'hr_dictCostPlaceType',
        JSON.stringify([
          { tn: 'hr_payEl' },
          { tn: 'hr_dictCostPlaceType' },
          { tn: 'hr_payEl', pfx: 'Включати види оплати за обліковим періодом' }])],
      [ 'sumAccFundKtg', 'Сума з нарахувань на зарплату за категоріями посад та МВВ', 'fileSAP',
        'hr_payFund', 'hr_dictCostPlaceType',
        JSON.stringify([
          { tn: 'hr_payFund' },
          { tn: 'hr_dictCostPlaceType' },
          { tn: 'hr_payFund', pfx: 'Включати види нарахувань на зарплату за обліковим періодом' }])],
      [ 'avgCountKtg', 'Середня кількість працівників за категоріями посад та МВВ', 'fileSAP',
        'hr_dictTimeCost', 'hr_dictCostPlaceType',
        JSON.stringify([
          { tn: 'hr_dictTimeCost' },
          { tn: 'hr_dictCostPlaceType' }])]
    ]
  }
]
