module.exports = [
  {
    entity: 'hr_method',
    identifier: ['code'],
    localeAttr: ['name'],
    attrsConfig: {
      methodGroupID: { associatedEntity: 'hr_methodGroup', codeAttr: 'code' }
    },
    attrs: ['code', 'name', 'methodGroupID', 'valuation', 'payElEntryType', 'dayAccumCondition', 'dayAverageCondition',
      'priority', 'payElEntrySum', 'payElEntryMinSum', 'payElEntryTime', 'payElEntryPlanSum'],
    items: [
      ['1', 'Погодинна за окладом', 1, 'SUM', null, null, null, null, null, null, null, null],
      ['2', 'Оплата за тарифом', 1, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['3', 'Оплата за договором ЦПХ', 1, 'SUM', null, null, null, null, null, null, null, null],
      ['4', 'Постійна надбавка', 2, 'SUMRATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['5', 'Надбавка за ранг', 2, 'SUMRATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['6', 'Надбавка за вислугу років', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['7', 'Доплата за роботу у вечірній час', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['8', 'Доплата за роботу у нічний час', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['9', 'Доплата за роботу в надурочний час', 2, 'SUMRATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['10', 'Доплата за роботу в святковий день', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['11', 'Оплата за роботу у вихідний день', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['12', 'Щомісячна премія', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['13', 'Відпустка', 4, 'SUMRATE', 'PAYMENT', 'noHolidays', 'noHolidays', null, null, null, null, null],
      ['14', 'Відпустка по догляду за дитиною до 3-х років', 4, 'NONE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['15', 'Відпустка без утримання', 4, 'NONE', 'PAYMENT', 'noDaysOff', 'noHolidays', null, null, null, null, null],
      ['16', 'Компенсація відпустки', 8, 'SUMRATE', 'PAYMENT', 'noHolidays', 'noHolidays', null, null, null, null, null],
      ['17', 'Лікарняні за рахунок підприємства', 5, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['18', 'Лікарняні за рахунок СС', 5, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['19', 'Лікарняний по догляду за рахунок СС', 5, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['20', 'Лікарняний по вагітності за рахунок СС', 5, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['21', 'Відрядження', 6, 'SUMRATE', 'PAYMENT', 'noDaysOff', 'work', null, null, null, null, null],
      ['22', 'Вихідна допомога', 6, 'SUMRATE', 'PAYMENT', null, 'work', null, null, null, null, null],
      ['23', 'Державні обов\'язки (оплата за середнім заробітком)', 6, 'SUMRATE', 'PAYMENT', 'noDaysOff', 'work', null, null, null, null, null],
      ['24', 'Індексація доходу', 8, 'DICT', 'PAYMENT', null, null, null, null, null, null, null],
      ['25', 'Доплата до мінімальної зарплати', 8, 'DICT', 'PAYMENT', null, null, 5, null, null, null, null],
      ['26', 'ПДФО', 127, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['27', 'Війсковий збір', 127, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['28', 'Виплата заробітної плати', 128, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['29', 'Аванс', 128, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['30', 'Виплата в міжрозрахунковий період', 128, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['31', 'Аліменти', 129, 'SUMRATE', 'PAYMENT,OFFTAKE', null, null, null, null, null, null, null],
      ['32', 'Профспілковий внесок', 130, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['33', 'Доплата за заміщення', 2, 'SUMRATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['34', 'Дивіденти', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['35', 'Авторська винагорода', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['36', 'Матеріальна допомога', 7, 'SUMRATE', 'PAYMENT', null, 'work', null, null, null, null, null],
      ['37', 'Матеріальна допомога на оздоровлення', 7, 'SUMRATE', 'PAYMENT', null, 'work', null, null, null, null, null],
      ['38', 'Матеріальна допомога на поховання за рахунок СС', 7, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['39', 'Благодійна або гуманітарна допомога', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['40', 'Лікарняний по нещасному випадку за рахунок СС', 5, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['41', 'Непідтверджений лікарняний', 5, 'SUMRATE', 'PAYMENT', 'noDaysOff', null, null, null, null, null, null],
      ['42', 'Разове нарахування', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['43', 'Разове утримання', 133, 'SUMRATE', 'OFFTAKE', null, null, null, null, null, null, null],
      ['44', 'Оплата за середнім заробітком', 1, 'SUMRATE', null, 'noDaysOff', 'work', null, null, null, null, null],
      ['45', 'Квартальна премія', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['46', 'Річна премія', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['47', 'Разова премія', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['48', 'Тимчасова непрацездатність', 5, 'SUMRATE', 'PAYMENT', 'noDaysOff', null, null, null, null, null, null],
      ['49', 'Доплата до мінімальної суми', 8, 'SUM', 'PAYMENT', null, null, 5, null, null, null, null],
      ['50', 'Доплата до середнього заробітку', 2, 'SUMRATE', 'PAYMENT', null, 'work', 5, null, null, null, null],
      ['51', 'Доплата при переведенні на легшу роботу за рахунок СС', 7, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['52', 'Відшкодування витрат на поховання за рахунок СС', 7, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['53', 'Виплата за рахунок СС', 128, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['54', 'Неявки з невідомої причини', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['55', 'Дохід від виграша (призи, лотереї)', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['56', 'Доплата до повного робочого дня', 2, 'DICT', 'PAYMENT', null, null, 5, null, null, null, null],
      ['57', 'Відпустка по догляду за дитиною до 6-х років', 4, 'SUMRATE', 'PAYMENT', 'noDaysOff', null, null, null, null, null, null],
      ['58', 'Компенсація вимушеного прогулу', 6, 'SUMRATE', 'PAYMENT', 'noDaysOff', 'work', null, null, null, null, null],
      ['59', 'Відрядження без наказа', 6, 'SUMRATE', 'PAYMENT', null, 'work', null, null, null, null, null],
      ['60', 'Компенсація переробітку (підсумований облік)', 7, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['61', 'Утримання за виконавчими листами', 129, 'SUMRATE', 'PAYMENT,OFFTAKE', null, null, null, null, null, null, null],
      ['62', 'Перерахування за заявою працівника', 130, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['63', 'Відрядна оплата', 1, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['64', 'Збір за рахунок платника', 129, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['65', 'Премія за період', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['66', 'Оплата за роботу в надурочний час', 2, 'PAYMENT', null, null, null, null, null, null, null, null],
      ['67', 'Навчальна відпустка', 4, 'SUMRATE', 'PAYMENT', 'calend', 'noHolidays', null, null, null, null, null],
      ['68', 'Військові збори', 6, 'SUMRATE', 'PAYMENT', 'noDaysOff', 'work', null, null, null, null, null],
      ['71', 'Залишок відпустки', 8, 'SUMRATE', 'PAYMENT', 'noHolidays', 'noHolidays', null, null, null, null, null],
      ['72', 'Перерахування залишку відпустки', 133, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['73', 'Донорські дні', 6, 'SUMRATE', 'PAYMENT', 'noDaysOff', 'work', null, null, null, null, null],
      ['74', 'Підвищення окладу', 1, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['75', 'Виплата за джерелом фінансування', 128, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['77', 'Стипендія', 1, 'SUM', null, null, null, null, null, null, null, null],
      ['134', 'Відпустка за вагітністю та пологами', 4, 'SUMRATE', 'PAYMENT', 'noDaysOff', 'work', null, null, null, null, null],
      ['135', 'Відшкодування вартості поховання за рахунок СС', 7, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['137', 'Оплата простою', 1, 'RATE', null, null, null, null, null, null, null, null],
      ['138', 'Переробіток', 2, 'SUMRATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['140', 'Відпустка по догляду за дитиною-інвалідом до 16/18 років', 4, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['141', 'Додаткове благо', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['142', 'Чорнобильска відпустка', 4, 'SUMRATE', 'PAYMENT', 'calend', 'noHolidays', null, null, null, null, null],
      ['143', 'Тарифна ставка', 1, 'SUMRATE', 'PAYMENT', null, null, 1, null, null, null, null],
      ['144', 'Підвищення тарифної ставки', 2, 'SUMRATE', 'PAYMENT', null, null, 2, '144', null, null, null],
      ['145', 'Тарифна ставка з підвищенням', 1, 'SUMRATE', 'PAYMENT', null, null, 3, null, null, null, null],
      ['146', 'Педагогічне навантаження', 1, 'SUMRATE', 'PAYMENT', null, null, 4, null, null, null, null],
      ['147', 'Адміністративна зарплата', 1, 'SUMRATE', 'PAYMENT', null, null, 4, null, null, null, null],
      ['148', 'Педагогічна надбавка (перевірка зошитів)', 2, 'SUMRATE', 'PAYMENT', null, null, 5, '1,2,3,44,63,74,137,143,146,147', null, '1,2,3,44,63,74,137,143,146,147,4,5,6,7,8,9,10,11,33,50,56,66,138,144,148,152', null],
      ['149', 'Лікарняний самоізоляція COVID-19', 5, 'SUMRATE', 'PAYMENT', 'calend', null, null, null, null, null, null],
      ['150', 'Заміна', 2, 'SUMRATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['151', 'Сума для розрахунку середнього заробітку', 9, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['152', 'Підвищення тарифної ставки за звання', 2, 'SUMRATE', 'PAYMENT', null, null, 2, null, null, null, null],
      ['153', 'Доплата за роботу у шкідливих умовах за табелем', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['154', 'Надбавка за класне керівництво', 2, 'SUMRATE', 'PAYMENT', null, null, 5, '1,2,3,44,63,74,137,143,146,147', null, '1,2,3,44,63,74,137,143,146,147,4,5,6,7,8,9,10,11,33,50,56,66,138,144,148,152', null],
      ['155', 'Надбавка за групу продовженого дня', 2, 'SUMRATE', 'PAYMENT', null, null, 5, '1,2,3,44,63,74,137,143,146,147', null, '1,2,3,44,63,74,137,143,146,147,4,5,6,7,8,9,10,11,33,50,56,66,138,144,148,152', null],
      ['156', 'Зарплата вихователя', 1, 'SUMRATE', 'PAYMENT', null, null, 4, null, null, null, null],
      ['201', 'Резерв відпусток (середній заробіток)', 134, 'SUM', 'PAYMENT', 'noHolidays', 'noHolidays', null, null, null, null, null],
      ['202', 'Резерв відпусток (відсоток від заробітку)', 134, 'RATE', 'PAYMENT', 'noHolidays', 'noHolidays', null, null, null, null, null],
      ['203', 'Інвентаризація резерву відпусток', 134, 'SUMRATE', 'PAYMENT', 'noHolidays', 'noHolidays', null, null, null, null, null],
      ['159', 'Змінний бригадний наряд', 1, 'SUMRATE', null, null, null, null, null, null, null, null],
      ['204', 'Доплата до чистої суми з обмеженням', 2, 'SUM', 'PAYMENT', null, null, 5, null, null, null, null],
      ['205', 'Премія чистою сумою з обмеженням', 3, 'SUM', 'PAYMENT', null, null, null, null, null, null, null],
      ['206', 'Премія за чистим плановим заробітком за період', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null],
      ['207', 'Доплата за особливі години роботи"', 2, 'RATE', 'PAYMENT', null, null, 5, null, null, null, null],
      ['208', 'Спеціальні методи розрахунку звільненим', 3, 'SUMRATE', 'PAYMENT', null, null, null, null, null, null, null]
    ]
  }
]
