module.exports = [
  {
    entity: 'hr_methodCfgAttr',
    identifier: ['methodID', 'attrName'],
    attrsConfig: {
      methodID: { associatedEntity: 'hr_method', codeAttr: 'code' }
    },
    attrs: ['methodID', 'attrName', 'notAllowBlank'],
    items: [
      ['1', 'calcProportion', 1],
      ['1', 'useTimeSheetBy', 1],
      ['1', 'payOverNorm', 1],
      ['1', 'isMtCount', 1],
      ['1', 'isAutoCalc', 1],
      ['1', 'isRecalculate', 1],
      ['1', 'roundUpTo', 1],
      ['1', 'dictFundSourceID', 0],
      ['1', 'entryOperationID', 0],
      ['1', 'dictTimeCostID', 0],

      ['2', 'calcProportion', 1],
      ['2', 'useTimeSheetBy', 1],
      ['2', 'payOverNorm', 1],
      ['2', 'isMtCount', 1],
      ['2', 'isAutoCalc', 1],
      ['2', 'isRecalculate', 1],
      ['2', 'roundUpTo', 1],
      ['2', 'dictFundSourceID', 0],
      ['2', 'entryOperationID', 0],

      ['3', 'isTimeSheet', 1],
      ['3', 'calcProportion', 0],
      ['3', 'useTimeSheetBy', 1],
      ['3', 'isAutoCalc', 1],
      ['3', 'isRecalculate', 1],
      ['3', 'dictFundSourceID', 0],
      ['3', 'entryOperationID', 0],

      ['4', 'calcSumType', 1],
      ['4', 'calcTimeProportion', 0],
      ['4', 'isMtCount', 1],
      ['4', 'isTimeSheet', 1],
      ['4', 'isAutoCalc', 1],
      ['4', 'isRecalculate', 1],
      ['4', 'roundUpTo', 1],
      ['4', 'dictFundSourceID', 0],
      ['4', 'entryOperationID', 0],
      ['4', 'isParentEmployeeNumber', 0],
      ['4', 'isLastEmployeeNumber', 0],
      ['4', 'isIndividualRate', 0],
      ['4', 'ignoreInCalcPay', 0],

      ['5', 'calcTimeProportion', 0],
      ['5', 'isAutoCalc', 1],
      ['5', 'isRecalculate', 1],
      ['5', 'roundUpTo', 1],
      ['5', 'dictFundSourceID', 0],
      ['5', 'entryOperationID', 0],

      ['6', 'calcSumType', 1],
      ['6', 'calcTimeProportion', 0],
      ['6', 'dictExperienceID', 1],
      ['6', 'isAutoCalc', 1],
      ['6', 'isRecalculate', 1],
      ['6', 'isTimeSheet', 0],
      ['6', 'roundUpTo', 1],
      ['6', 'dictFundSourceID', 0],
      ['6', 'entryOperationID', 0],
      ['6', 'surchargeExperience', 0],

      ['7', 'useTimeSheetBy', 1],
      ['7', 'normTimeBy', 1],
      ['7', 'maxMtCount', 0],
      ['7', 'isAutoCalc', 1],
      ['7', 'isRecalculate', 1],
      ['7', 'roundUpTo', 1],
      ['7', 'dictFundSourceID', 0],
      ['7', 'entryOperationID', 0],

      ['8', 'useTimeSheetBy', 1],
      ['8', 'normTimeBy', 1],
      ['8', 'maxMtCount', 0],
      ['8', 'isAutoCalc', 1],
      ['8', 'isRecalculate', 1],
      ['8', 'roundUpTo', 1],
      ['8', 'dictFundSourceID', 0],
      ['8', 'entryOperationID', 0],

      ['9', 'isAutoCalc', 1],
      ['9', 'isRecalculate', 1],
      ['9', 'roundUpTo', 1],
      ['9', 'dictFundSourceID', 0],
      ['9', 'entryOperationID', 0],

      ['10', 'useTimeSheetBy', 1],
      ['10', 'normTimeBy', 1],
      ['10', 'maxMtCount', 0],
      ['10', 'calcTimeProportion', 0],
      ['10', 'isAutoCalc', 1],
      ['10', 'isRecalculate', 1],
      ['10', 'roundUpTo', 1],
      ['10', 'dictFundSourceID', 0],
      ['10', 'entryOperationID', 0],

      ['11', 'useTimeSheetBy', 1],
      ['11', 'normTimeBy', 1],
      ['11', 'maxMtCount', 0],
      ['11', 'calcTimeProportion', 0],
      ['11', 'isPayInHolidays', 0],
      ['11', 'isAutoCalc', 1],
      ['11', 'isRecalculate', 1],
      ['11', 'roundUpTo', 1],
      ['11', 'dictFundSourceID', 0],
      ['11', 'entryOperationID', 0],

      ['12', 'periodType', 1],
      ['12', 'isTimeSheet', 1],
      ['12', 'isAutoCalc', 1],
      ['12', 'isRecalculate', 1],
      ['12', 'roundUpTo', 1],
      ['12', 'dictFundSourceID', 0],
      ['12', 'entryOperationID', 0],
      ['12', 'isParentEmployeeNumber', 0],
      ['12', 'isLastEmployeeNumber', 0],
      ['12', 'isIndividualRate', 0],
      ['12', 'includeInCalcAvg', 0],
      ['12', 'useKPI', 0],
      ['12', 'isPayDismAll', 0],
      ['12', 'isPayDismSalPeriod', 0],
      ['12', 'isPayDismCalcPeriod', 0],
      ['12', 'isPayDismOnlyPeriod', 0],

      ['13', 'calcMounth', 1],
      ['13', 'isRecalculate', 1],
      ['13', 'roundAverage', 1],
      ['13', 'roundAvgUpTo', 1],
      ['13', 'dictTimeCostID', 1],
      ['13', 'roundUpTo', 1],
      ['13', 'dictFundSourceID', 0],
      ['13', 'entryOperationID', 0],
      ['13', 'includeSecondJobs', 0],
      ['13', 'isParentEmployeeNumber', 0],
      ['13', 'isCorrectPlan', 0],
      ['13', 'usePartialFirstMonth', 0],

      ['14', 'isAutoCalc', 1],
      ['14', 'isRecalculate', 1],
      ['14', 'dictFundSourceID', 0],
      ['14', 'entryOperationID', 0],
      ['14', 'dictTimeCostID', 1],
      ['14', 'includeSecondJobs', 0],

      ['15', 'isAutoCalc', 1],
      ['15', 'isRecalculate', 1],
      ['15', 'dictTimeCostID', 1],
      ['15', 'dictFundSourceID', 0],
      ['15', 'entryOperationID', 0],
      ['15', 'includeSecondJobs', 0],

      ['16', 'calcMounth', 1],
      ['16', 'isRecalculate', 1],
      ['16', 'roundAverage', 1],
      ['16', 'roundUpTo', 1],
      ['16', 'roundAvgUpTo', 1],
      ['16', 'dictFundSourceID', 0],
      ['16', 'entryOperationID', 0],
      ['16', 'includeSecondJobs', 0],
      ['16', 'isParentEmployeeNumber', 0],
      ['16', 'isCorrectPlan', 0],
      ['16', 'usePartialFirstMonth', 0],

      ['17', 'dictTimeCostID', 1],
      ['17', 'calcMounth', 1],
      ['17', 'dictExperienceID', 1],
      ['17', 'roundAverage', 1],
      ['17', 'roundUpTo', 1],
      ['17', 'roundAvgUpTo', 1],
      ['17', 'isRecalculate', 1],
      ['17', 'dictFundSourceID', 0],
      ['17', 'entryOperationID', 0],
      ['17', 'includeSecondJobs', 0],
      ['17', 'isParentEmployeeNumber', 0],
      ['17', 'isCorrectPlan', 0],
      ['17', 'excludeMonthFreeDays', 0],

      ['18', 'dictTimeCostID', 1],
      ['18', 'calcMounth', 1],
      ['18', 'dictExperienceID', 1],
      ['18', 'roundAverage', 1],
      ['18', 'roundUpTo', 1],
      ['18', 'roundAvgUpTo', 1],
      ['18', 'isRecalculate', 1],
      ['18', 'dictFundSourceID', 0],
      ['18', 'entryOperationID', 0],
      ['18', 'includeSecondJobs', 0],
      ['18', 'isParentEmployeeNumber', 0],
      ['18', 'isCorrectPlan', 0],
      ['18', 'excludeMonthFreeDays', 0],

      ['19', 'dictTimeCostID', 1],
      ['19', 'calcMounth', 1],
      ['19', 'dictExperienceID', 1],
      ['19', 'roundAverage', 1],
      ['19', 'roundUpTo', 1],
      ['19', 'roundAvgUpTo', 1],
      ['19', 'isRecalculate', 1],
      ['19', 'dictFundSourceID', 0],
      ['19', 'entryOperationID', 0],
      ['19', 'includeSecondJobs', 0],
      ['19', 'isParentEmployeeNumber', 0],
      ['19', 'isCorrectPlan', 0],
      ['19', 'excludeMonthFreeDays', 0],

      ['20', 'dictTimeCostID', 1],
      ['20', 'calcMounth', 1],
      ['20', 'dictExperienceID', 1],
      ['20', 'roundAverage', 1],
      ['20', 'roundUpTo', 1],
      ['20', 'roundAvgUpTo', 1],
      ['20', 'dictFundSourceID', 0],
      ['20', 'entryOperationID', 0],
      ['20', 'isRecalculate', 0],
      ['20', 'includeSecondJobs', 0],
      ['20', 'isParentEmployeeNumber', 0],
      ['20', 'isCorrectPlan', 0],
      ['20', 'excludeMonthFreeDays', 0],

      ['21', 'calcMounth', 1],
      ['21', 'roundAverage', 1],
      ['21', 'dictTimeCostWorkID', 1],
      ['21', 'dictTimeCostAvgID', 1],
      ['21', 'isRecalculate', 1],
      ['21', 'roundUpTo', 1],
      ['21', 'roundAvgUpTo', 1],
      ['21', 'dictFundSourceID', 0],
      ['21', 'entryOperationID', 0],
      ['21', 'onlyPlanTrip', 0],
      ['21', 'includeSecondJobs', 0],
      ['21', 'calcIndAvgType', 1],
      ['21', 'accrueFuturePeriod', 0],
      ['21', 'isParentEmployeeNumber', 0],
      ['21', 'calcEarnings', 0],
      ['21', 'dayAccumCondition', 1],
      ['21', 'usePartialFirstMonth', 0],
      ['21', 'calcByDayEarnPermAcc', 0],
      ['21', 'dayEarningType', 1],
      ['21', 'calcEachPeriod', 0],

      ['22', 'calcMounth', 1],
      ['22', 'roundAverage', 1],
      ['22', 'roundUpTo', 1],
      ['22', 'roundAvgUpTo', 1],
      ['22', 'isRecalculate', 1],
      ['22', 'dictFundSourceID', 0],
      ['22', 'entryOperationID', 0],
      ['22', 'onlyPlanTrip', 0],
      ['22', 'includeSecondJobs', 0],
      ['22', 'calcEarnings', 0],
      ['22', 'usePartialFirstMonth', 0],

      ['23', 'calcMounth', 1],
      ['23', 'roundAverage', 1],
      ['23', 'accrualRate', 0],
      ['23', 'dictTimeCostID', 1],
      ['23', 'roundUpTo', 1],
      ['23', 'roundAvgUpTo', 1],
      ['23', 'isRecalculate', 1],
      ['23', 'dictFundSourceID', 0],
      ['23', 'entryOperationID', 0],
      ['23', 'onlyPlanTrip', 0],
      ['23', 'includeSecondJobs', 0],
      ['23', 'accrueFuturePeriod', 0],
      ['23', 'calcEarnings', 0],
      ['23', 'isCorrectPlan', 0],
      ['23', 'usePartialFirstMonth', 0],

      ['24', 'isAutoCalc', 1],
      ['24', 'isRecalculate', 1],
      ['24', 'roundUpTo', 1],
      ['24', 'dictFundSourceID', 0],
      ['24', 'entryOperationID', 0],
      ['24', 'calcSumType', 1],
      // ['24', 'includeSecondJobs', 1],

      ['25', 'isNormMinSum', 1],
      ['25', 'maxMtCount', 0],
      ['25', 'isAutoCalc', 1],
      ['25', 'isRecalculate', 1],
      ['25', 'roundUpTo', 1],
      ['25', 'dictFundSourceID', 0],
      ['25', 'entryOperationID', 0],
      ['25', 'includeSecondJobs', 0],

      ['26', 'periodType', 1],
      ['26', 'notUseBenefits', 1],
      ['26', 'isAutoCalc', 1],
      ['26', 'isRecalculate', 1],
      ['26', 'roundUpTo', 1],
      ['26', 'dictFundSourceID', 0],
      ['26', 'entryOperationID', 0],

      ['27', 'periodType', 1],
      ['27', 'roundAvera1e', 1],
      ['27', 'includeSecondJobs', 0],
      ['27', 'isAutoCalc', 1],
      ['27', 'isRecalculate', 1],
      ['27', 'roundUpTo', 1],
      ['27', 'dictFundSourceID', 0],
      ['27', 'entryOperationID', 0],

      ['28', 'dictFundSourceID', 0],
      ['28', 'entryOperationID', 0],
      ['28', 'roundUpTo', 1],
      ['28', 'includeSecondJobs', 0],

      ['29', 'typePrepayment', 1],
      ['29', 'percPrepayment', 0],
      ['29', 'prepaymentDay', 1],
      ['29', 'excludePartTimeEmp', 1],
      ['29', 'hiredThisMonth', 1],
      ['29', 'isAutoCalc', 1],
      ['29', 'isRecalculate', 1],
      ['29', 'roundUpTo', 1],
      ['29', 'dictFundSourceID', 0],
      ['29', 'entryOperationID', 0],
      ['29', 'includeSecondJobs', 0],
      ['29', 'paymentIfNotLess', 0],

      ['30', 'dictFundSourceID', 0],
      ['30', 'entryOperationID', 0],
      ['30', 'roundUpTo', 1],
      ['30', 'includeSecondJobs', 0],

      ['31', 'alimonyLessPayment', 1],
      ['31', 'includeSecondJobs', 0],
      ['31', 'typeCalcTime', 1],
      ['31', 'repaymentOnly', 0],
      ['31', 'isAutoCalc', 1],
      ['31', 'isRecalculate', 1],
      ['31', 'roundUpTo', 1],
      ['31', 'dictFundSourceID', 0],
      ['31', 'entryOperationID', 0],

      ['32', 'periodType', 1],
      ['32', 'roundAverage', 1],
      ['32', 'includeSecondJobs', 0],
      ['32', 'isAutoCalc', 1],
      ['32', 'isRecalculate', 1],
      ['32', 'roundUpTo', 1],
      ['32', 'dictFundSourceID', 0],
      ['32', 'entryOperationID', 0],

      ['33', 'maxMtCount', 0],
      ['33', 'useTimeSheetBy', 1],
      ['33', 'calcAlgorithm', 0],
      ['33', 'calcTimeProportion', 0],
      ['33', 'isAutoCalc', 1],
      ['33', 'isRecalculate', 1],
      ['33', 'roundUpTo', 1],
      ['33', 'dictFundSourceID', 0],
      ['33', 'entryOperationID', 0],

      ['36', 'calcMounth', 1],
      ['36', 'roundAverage', 1],
      ['36', 'roundUpTo', 1],
      ['36', 'roundAvgUpTo', 1],
      ['36', 'dictExperienceID', 0],
      ['36', 'dictFundSourceID', 0],
      ['36', 'entryOperationID', 0],
      ['36', 'calcAvgType', 0],
      ['36', 'isRecalculate', 0],
      ['36', 'onlyPlanTrip', 0],
      ['36', 'isParentEmployeeNumber', 0],
      ['36', 'notLimitPayments', 0],
      ['36', 'usePartialFirstMonth', 0],

      ['37', 'calcMounth', 1],
      ['37', 'roundAverage', 1],
      ['37', 'roundUpTo', 1],
      ['37', 'roundAvgUpTo', 1],
      ['37', 'dictExperienceID', 0],
      ['37', 'dictFundSourceID', 0],
      ['37', 'entryOperationID', 0],
      ['37', 'calcAvgType', 1],
      ['37', 'isRecalculate', 0],
      ['37', 'onlyPlanTrip', 0],
      ['37', 'isParentEmployeeNumber', 0],
      ['37', 'isCorrectPlan', 0],
      ['37', 'usePartialFirstMonth', 0],

      ['38', 'dictFundSourceID', 0],
      ['38', 'entryOperationID', 0],

      ['40', 'includeSecondJobs', 0],
      ['40', 'dictTimeCostID', 1],
      ['40', 'calcMounth', 1],
      ['40', 'dictExperienceID', 1],
      ['40', 'roundAverage', 1],
      ['40', 'roundUpTo', 1],
      ['40', 'roundAvgUpTo', 1],
      ['40', 'isRecalculate', 1],
      ['40', 'dictFundSourceID', 0],
      ['40', 'entryOperationID', 0],
      ['40', 'isParentEmployeeNumber', 0],
      ['40', 'isCorrectPlan', 0],
      ['40', 'excludeMonthFreeDays', 0],

      ['41', 'dictTimeCostID', 1],
      ['41', 'includeSecondJobs', 0],

      ['42', 'dictFundSourceID', 0],
      ['42', 'entryOperationID', 0],
      ['42', 'ignoreInCalcPay', 0],

      ['43', 'dictFundSourceID', 0],
      ['43', 'entryOperationID', 0],
      ['43', 'ignoreInCalcPay', 0],

      ['44', 'calcMounth', 1],
      ['44', 'roundAverage', 1],
      ['44', 'accrualRate', 0],
      ['44', 'dictTimeCostID', 1],
      ['44', 'isAutoCalc', 1],
      ['44', 'isRecalculate', 1],
      ['44', 'roundUpTo', 1],
      ['44', 'roundAvgUpTo', 1],
      ['44', 'dictFundSourceID', 0],
      ['44', 'entryOperationID', 0],
      ['44', 'onlyPlanTrip', 0],
      ['44', 'accrueFuturePeriod', 0],
      ['44', 'calcEarnings', 0],
      ['44', 'isParentEmployeeNumber', 0],
      ['44', 'isCorrectPlan', 0],

      ['45', 'calcSumType', 1],
      ['45', 'periodType', 0],
      ['45', 'isRecalculate', 1],
      ['45', 'roundUpTo', 1],
      ['45', 'dictFundSourceID', 0],
      ['45', 'entryOperationID', 0],
      ['45', 'isParentEmployeeNumber', 0],
      ['45', 'isLastEmployeeNumber', 0],
      ['45', 'isIndividualRate', 0],
      ['45', 'includeInCalcAvg', 0],
      ['45', 'baseSumIsAverage', 0],
      ['45', 'calcTimeProportion', 1],

      ['46', 'calcSumType', 1],
      ['46', 'periodType', 0],
      ['46', 'dictExperienceID', 1],
      ['46', 'isRecalculate', 1],
      ['46', 'roundUpTo', 1],
      ['46', 'dictFundSourceID', 0],
      ['46', 'entryOperationID', 0],
      ['46', 'isParentEmployeeNumber', 0],
      ['46', 'isLastEmployeeNumber', 0],
      ['46', 'isIndividualRate', 0],
      ['46', 'includeInCalcAvg', 0],
      ['46', 'baseSumIsAverage', 0],
      ['46', 'calcTimeProportion', 1],

      ['47', 'calcSumType', 1],
      ['47', 'periodType', 0],
      ['47', 'isMtCount', 1],
      ['47', 'isTimeSheet', 1],
      ['47', 'isRecalculate', 1],
      ['47', 'roundUpTo', 1],
      ['47', 'dictFundSourceID', 0],
      ['47', 'entryOperationID', 0],
      ['47', 'isParentEmployeeNumber', 0],
      ['47', 'isLastEmployeeNumber', 0],
      ['47', 'isIndividualRate', 0],
      ['47', 'includeInCalcAvg', 0],
      ['47', 'baseSumIsAverage', 0],
      ['47', 'calcTimeProportion', 1],
      ['47', 'maxMtCount', 0],

      ['48', 'dictTimeCostID', 1],
      ['48', 'calcMounth', 1],
      ['48', 'dictExperienceID', 1],
      ['48', 'roundAverage', 1],
      ['48', 'roundUpTo', 1],
      ['48', 'dictFundSourceID', 0],
      ['48', 'entryOperationID', 0],
      ['48', 'includeSecondJobs', 0],

      ['49', 'isNormMinSum', 1],
      ['49', 'maxMtCount', 0],
      ['49', 'isAutoCalc', 1],
      ['49', 'isRecalculate', 1],
      ['49', 'roundUpTo', 1],
      ['49', 'dictFundSourceID', 0],
      ['49', 'entryOperationID', 0],
      ['49', 'includeSecondJobs', 0],
      ['49', 'isMtCount', 0],

      ['50', 'calcMounth', 1],
      ['50', 'roundAverage', 1],
      ['50', 'roundUpTo', 1],
      ['50', 'roundAvgUpTo', 1],
      ['50', 'dictFundSourceID', 0],
      ['50', 'entryOperationID', 0],
      ['50', 'onlyPlanTrip', 0],
      ['50', 'includeSecondJobs', 0],

      ['51', 'calcMounth', 1],
      ['51', 'roundAverage', 1],
      ['51', 'roundUpTo', 1],
      ['51', 'roundAvgUpTo', 1],
      ['51', 'dictFundSourceID', 0],
      ['51', 'entryOperationID', 0],
      ['51', 'onlyPlanTrip', 0],

      ['53', 'dictFundSourceID', 0],
      ['53', 'entryOperationID', 0],

      ['56', 'calcTimeProportion', 0],
      ['56', 'isAutoCalc', 1],
      ['56', 'isRecalculate', 1],
      ['56', 'roundUpTo', 1],
      ['56', 'dictFundSourceID', 0],
      ['56', 'entryOperationID', 0],

      ['57', 'isAutoCalc', 1],
      ['57', 'isRecalculate', 1],
      ['57', 'dictFundSourceID', 0],
      ['57', 'entryOperationID', 0],
      ['57', 'dictTimeCostID', 1],
      ['57', 'includeSecondJobs', 0],

      ['58', 'dictTimeCostID', 1],
      ['58', 'isRecalculate', 0],
      ['58', 'calcMounth', 1],
      ['58', 'roundAverage', 1],
      ['58', 'roundUpTo', 1],
      ['58', 'roundAvgUpTo', 1],
      ['58', 'dictFundSourceID', 0],
      ['58', 'entryOperationID', 0],
      ['58', 'onlyPlanTrip', 0],
      ['58', 'includeSecondJobs', 0],
      ['58', 'isParentEmployeeNumber', 0],
      ['58', 'calcEarnings', 0],
      ['58', 'usePartialFirstMonth', 0],

      ['59', 'includeSecondJobs', 0],

      ['61', 'includeSecondJobs', 0],
      ['61', 'alimonyLessPayment', 0],
      ['61', 'repaymentOnly', 0],
      ['61', 'notReqReport', 0],
      ['61', 'isAutoCalc', 1],
      ['61', 'isRecalculate', 1],
      ['61', 'roundUpTo', 1],
      ['61', 'dictFundSourceID', 0],
      ['61', 'entryOperationID', 0],

      ['62', 'calcSumType', 1],
      ['62', 'periodType', 1],
      ['62', 'isAutoCalc', 1],
      ['62', 'isRecalculate', 1],
      ['62', 'roundUpTo', 1],
      ['62', 'dictFundSourceID', 0],
      ['62', 'entryOperationID', 0],

      ['63', 'useTimeSheetBy', 1],
      ['63', 'isAutoCalc', 1],
      ['63', 'isRecalculate', 1],
      ['63', 'dictTimeCostID', 1],

      ['65', 'calcSumType', 1],
      ['65', 'periodType', 0],
      ['65', 'isRecalculate', 1],
      ['65', 'roundUpTo', 1],
      ['65', 'dictFundSourceID', 0],
      ['65', 'entryOperationID', 0],
      ['65', 'isTimeSheet', 0],
      ['65', 'isParentEmployeeNumber', 0],
      ['65', 'isLastEmployeeNumber', 0],
      ['65', 'isIndividualRate', 0],
      ['65', 'includeInCalcAvg', 0],
      ['65', 'baseSumIsAverage', 0],
      ['65', 'calcTimeProportion', 1],

      ['67', 'calcMounth', 1],
      ['67', 'isRecalculate', 1],
      ['67', 'roundAverage', 1],
      ['67', 'dictTimeCostID', 1],
      ['67', 'roundUpTo', 1],
      ['67', 'roundAvgUpTo', 1],
      ['67', 'dictFundSourceID', 0],
      ['67', 'entryOperationID', 0],
      ['67', 'includeSecondJobs', 0],
      ['67', 'isParentEmployeeNumber', 0],
      ['67', 'isCorrectPlan', 0],
      ['67', 'usePartialFirstMonth', 0],

      ['68', 'calcMounth', 1],
      ['68', 'roundAverage', 1],
      ['68', 'roundAvgUpTo', 1],
      ['68', 'accrualRate', 0],
      ['68', 'dictTimeCostID', 0],
      ['68', 'roundUpTo', 1],
      ['68', 'isRecalculate', 1],
      ['68', 'dictFundSourceID', 0],
      ['68', 'entryOperationID', 0],
      ['68', 'onlyPlanTrip', 0],
      ['68', 'includeSecondJobs', 0],
      ['68', 'isParentEmployeeNumber', 0],
      ['68', 'usePartialFirstMonth', 0],

      ['71', 'calcMounth', 1],
      ['71', 'isRecalculate', 1],
      ['71', 'roundAverage', 1],
      ['71', 'roundUpTo', 1],
      ['71', 'roundAvgUpTo', 1],
      ['71', 'dictFundSourceID', 0],
      ['71', 'entryOperationID', 0],
      ['71', 'includeSecondJobs', 0],
      ['71', 'isParentEmployeeNumber', 0],
      ['71', 'usePartialFirstMonth', 0],

      ['72', 'includeSecondJobs', 0],

      ['73', 'calcMounth', 1],
      ['73', 'roundAverage', 1],
      ['73', 'dictTimeCostID', 1],
      ['73', 'accrualRate', 0],
      ['73', 'roundUpTo', 1],
      ['73', 'roundAvgUpTo', 1],
      ['73', 'isRecalculate', 1],
      ['73', 'dictFundSourceID', 0],
      ['73', 'entryOperationID', 0],
      ['73', 'onlyPlanTrip', 0],
      ['73', 'includeSecondJobs', 0],
      ['73', 'accrueFuturePeriod', 0],
      ['73', 'calcEarnings', 0],
      ['73', 'isParentEmployeeNumber', 0],
      ['73', 'isCorrectPlan', 0],
      ['73', 'usePartialFirstMonth', 0],

      ['74', 'roundUpTo', 1],
      ['74', 'ignoreInCalcPay', 1],
      ['74', 'isAutoCalc', 1],
      ['74', 'isRecalculate', 1],

      ['75', 'dictFundSourceID', 0],
      ['75', 'entryOperationID', 0],
      ['75', 'roundUpTo', 1],
      ['75', 'includeSecondJobs', 0],

      ['77', 'calcProportion', 1],
      ['77', 'useTimeSheetBy', 1],
      ['77', 'isMtCount', 1],
      ['77', 'isAutoCalc', 1],
      ['77', 'isRecalculate', 1],
      ['77', 'roundUpTo', 1],
      ['77', 'dictFundSourceID', 0],
      ['77', 'entryOperationID', 0],
      ['77', 'dictTimeCostID', 0],

      ['134', 'includeSecondJobs', 0],

      ['135', 'dictFundSourceID', 0],
      ['135', 'entryOperationID', 0],

      ['137', 'calcTimeProportion', 1],
      ['137', 'useTimeSheetBy', 1],
      ['137', 'dictTimeCostID', 0],
      ['137', 'accrualRate', 0],
      ['137', 'isMtCount', 0],
      ['137', 'maxMtCount', 0],
      ['137', 'payDownTime', 0],
      ['137', 'useTimeSheetBy', 1],
      ['137', 'isAutoCalc', 1],
      ['137', 'isRecalculate', 1],
      ['137', 'roundUpTo', 1],
      ['137', 'dictFundSourceID', 0],
      ['137', 'entryOperationID', 0],

      ['138', 'periodSummarized', 1],
      ['138', 'useTimeSheetBy', 1],
      ['138', 'isAutoCalc', 1],
      ['138', 'isRecalculate', 1],
      ['138', 'roundUpTo', 1],
      ['138', 'dictFundSourceID', 0],
      ['138', 'entryOperationID', 0],

      ['140', 'isAutoCalc', 1],
      ['140', 'isRecalculate', 1],
      ['140', 'dictFundSourceID', 0],
      ['140', 'entryOperationID', 0],
      ['140', 'dictTimeCostID', 1],
      ['140', 'includeSecondJobs', 0],

      ['141', 'dictFundSourceID', 0],
      ['141', 'entryOperationID', 0],
      ['141', 'ignoreInCalcPay', 1],

      ['142', 'calcMounth', 1],
      ['142', 'isRecalculate', 1],
      ['142', 'roundAverage', 1],
      ['142', 'dictTimeCostID', 1],
      ['142', 'roundUpTo', 1],
      ['142', 'roundAvgUpTo', 1],
      ['142', 'dictFundSourceID', 0],
      ['142', 'entryOperationID', 0],
      ['142', 'includeSecondJobs', 0],
      ['142', 'isParentEmployeeNumber', 0],
      ['142', 'isCorrectPlan', 0],
      ['142', 'usePartialFirstMonth', 0],

      ['144', 'dictTarifCoeffID', 0],

      ['146', 'calcProportion', 1],
      ['146', 'useTimeSheetBy', 1],
      ['146', 'isMtCount', 1],
      ['146', 'isAutoCalc', 1],
      ['146', 'isRecalculate', 1],
      ['146', 'roundUpTo', 1],
      ['146', 'dictFundSourceID', 0],
      ['146', 'entryOperationID', 0],

      ['147', 'calcProportion', 1],
      ['147', 'useTimeSheetBy', 1],
      ['147', 'isMtCount', 0],
      ['147', 'isAutoCalc', 1],
      ['147', 'isRecalculate', 1],
      ['147', 'roundUpTo', 1],
      ['147', 'dictFundSourceID', 0],
      ['147', 'entryOperationID', 0],

      ['148', 'isAutoCalc', 1],
      ['148', 'isRecalculate', 1],
      ['148', 'roundUpTo', 1],
      ['148', 'dictFundSourceID', 0],
      ['148', 'entryOperationID', 0],

      ['149', 'dictTimeCostID', 1],
      ['149', 'calcMounth', 1],
      ['149', 'dictExperienceID', 1],
      ['149', 'roundAverage', 1],
      ['149', 'roundUpTo', 1],
      ['149', 'roundAvgUpTo', 1],
      ['149', 'isRecalculate', 1],
      ['149', 'dictFundSourceID', 0],
      ['149', 'entryOperationID', 0],
      ['149', 'includeSecondJobs', 0],
      ['149', 'isParentEmployeeNumber', 0],
      ['149', 'isCorrectPlan', 0],
      ['149', 'excludeMonthFreeDays', 0],

      ['150', 'roundUpTo', 1],
      // ['150', 'isRecalculate', 1],
      ['150', 'dictFundSourceID', 0],
      ['150', 'entryOperationID', 0],

      ['151', 'dictFundSourceID', 0],
      ['151', 'ignoreInCalcPay', 1],

      ['152', 'dictTarifCoeffID', 0],

      ['153', 'useTimeSheetBy', 1],
      ['153', 'normTimeBy', 1],
      ['153', 'maxMtCount', 0],
      ['153', 'isAutoCalc', 1],
      ['153', 'isRecalculate', 1],
      ['153', 'roundUpTo', 1],
      ['153', 'dictFundSourceID', 0],
      ['153', 'entryOperationID', 0],

      ['154', 'isAutoCalc', 1],
      ['154', 'isRecalculate', 1],
      ['154', 'roundUpTo', 1],
      ['154', 'dictFundSourceID', 0],
      ['154', 'entryOperationID', 0],

      ['155', 'isAutoCalc', 1],
      ['155', 'isRecalculate', 1],
      ['155', 'roundUpTo', 1],
      ['155', 'dictFundSourceID', 0],
      ['155', 'entryOperationID', 0],

      ['156', 'calcProportion', 1],
      ['156', 'useTimeSheetBy', 1],
      ['156', 'isMtCount', 0],
      ['156', 'isAutoCalc', 1],
      ['156', 'isRecalculate', 1],
      ['156', 'roundUpTo', 1],
      ['156', 'dictFundSourceID', 0],
      ['156', 'entryOperationID', 0],

      ['159', 'isAutoCalc', 1],
      ['159', 'isRecalculate', 1],
      ['159', 'roundUpTo', 1],
      ['159', 'dictFundSourceID', 0],
      ['159', 'entryOperationID', 0],
      ['159', 'dictTimeCostID', 0],
      ['159', 'useDictTech', 0],

      ['201', 'calcMounth', 1],
      ['201', 'isCalcReservePart', 1],
      ['201', 'isAutoCalc', 1],
      ['201', 'roundAverage', 1],
      ['201', 'roundUpTo', 1],
      ['201', 'roundAvgUpTo', 1],
      ['201', 'dictFundSourceID', 0],
      ['201', 'entryOperationID', 0],
      ['201', 'includeSecondJobs', 0],
      ['201', 'isParentEmployeeNumber', 0],
      ['201', 'isCorrectPlan', 0],
      ['201', 'ignoreInCalcPay', 1],
      ['201', 'usePartialFirstMonth', 0],

      ['202', 'isAutoCalc', 1],
      ['202', 'roundAverage', 1],
      ['202', 'roundUpTo', 1],
      ['202', 'dictFundSourceID', 0],
      ['202', 'entryOperationID', 0],
      ['202', 'includeSecondJobs', 0],
      ['202', 'isParentEmployeeNumber', 0],
      ['202', 'ignoreInCalcPay', 1],

      ['203', 'calcMounth', 1],
      ['203', 'isAutoCalc', 1],
      ['203', 'roundAverage', 1],
      ['203', 'roundUpTo', 1],
      ['203', 'roundAvgUpTo', 1],
      ['203', 'dictFundSourceID', 0],
      ['203', 'entryOperationID', 0],
      ['203', 'includeSecondJobs', 0],
      ['203', 'isParentEmployeeNumber', 0],
      ['203', 'isCorrectPlan', 0],
      ['203', 'ignoreInCalcPay', 1],
      ['203', 'usePartialFirstMonth', 0],

      ['204', 'calcTimeProportion', 0],
      ['204', 'isMtCount', 0],
      ['204', 'sumPayMore', 1],
      ['204', 'isTimeSheet', 0],
      ['204', 'isLimitTimeSheet', 0],
      ['204', 'includeSecondJobs', 0],
      ['204', 'roundUpTo', 1],
      ['204', 'isAutoCalc', 1],
      ['204', 'isRecalculate', 1],
      ['204', 'dictFundSourceID', 0],
      ['204', 'entryOperationID', 0],

      ['205', 'calcTimeProportion', 0],
      ['205', 'isMtCount', 0],
      ['205', 'sumPayMore', 1],
      ['205', 'isTimeSheet', 0],
      ['205', 'isLimitTimeSheet', 0],
      ['205', 'includeSecondJobs', 0],
      ['205', 'roundUpTo', 1],
      ['205', 'isAutoCalc', 1],
      ['205', 'isRecalculate', 1],
      ['205', 'dictFundSourceID', 0],
      ['205', 'entryOperationID', 0],
      ['205', 'isPayDismAll', 0],
      ['205', 'isPayDismSalPeriod', 0],
      ['205', 'isPayDismCalcPeriod', 0],
      ['205', 'isPayDismOnlyPeriod', 0],

      ['206', 'calcPlanType', 1],
      ['206', 'isParentEmployeeNumber', 0],
      ['206', 'roundUpTo', 1],
      ['206', 'dictFundSourceID', 0],
      ['206', 'entryOperationID', 0],

      ['207', 'useTimeSheetBy', 1],
      ['207', 'normTimeBy', 1],
      ['207', 'maxMtCount', 0],
      ['207', 'isAutoCalc', 1],
      ['207', 'isRecalculate', 1],
      ['207', 'roundUpTo', 1],
      ['207', 'dictFundSourceID', 0],
      ['207', 'entryOperationID', 0],

      ['208', 'payElID', 1],
      ['208', 'rightRate', 1],
      ['208', 'calcMounthRate', 1],
      ['208', 'roundUpTo', 1],
      ['208', 'isAutoCalc', 1],
      ['208', 'isRecalculate', 1],
      ['208', 'dictFundSourceID', 0],
      ['208', 'entryOperationID', 0]
    ]
  }
]
