module.exports = [
  {
    entity: 'hr_methodCfgPanel',
    identifier: ['methodID', 'cfgPanelID'],
    attrsConfig: {
      methodID: { associatedEntity: 'hr_method', codeAttr: 'code' },
      cfgPanelID: { associatedEntity: 'hr_cfgPanel', codeAttr: 'code' },
      cfgPanelNameID: { associatedEntity: 'hr_cfgPanelName', codeAttr: 'code' }
    },
    attrs: ['methodID', 'cfgPanelID', 'sortOrder', 'cfgPanelNameID'],
    items: [
      ['1', 'property', 1, null],
      ['1', 'payElTimeCost', 2, null],
      ['1', 'payElEntrySum', 3, '4'],
      ['1', 'payElFundSource', 4, null],
      ['1', 'additionalParams', 5, null],

      ['2', 'property', 1, null],
      ['2', 'payElTimeCost', 2, null],
      ['2', 'payElFundSource', 3, null],
      ['2', 'additionalParams', 4, null],

      ['3', 'property', 1, null],
      ['3', 'payElTimeCost', 2, null],
      ['3', 'payElFundSource', 3, null],
      ['3', 'additionalParams', 4, null],

      ['4', 'property', 1, null],
      ['4', 'payElEntrySum', 2, null],
      ['4', 'payElEntryTime', 3, null],
      ['4', 'payElFundSource', 4, null],
      ['4', 'additionalParams', 5, null],

      ['5', 'property', 1, null],
      ['5', 'payElEntryTime', 2, null],
      ['5', 'payElFundSource', 3, null],
      ['5', 'additionalParams', 4, null],

      ['6', 'property', 1, null],
      ['6', 'payElEntrySum', 1, null],
      ['6', 'payElEntryTime', 2, null],
      ['6', 'payElExperience', 3, null],
      ['6', 'payElFundSource', 4, null],
      ['6', 'additionalParams', 5, null],

      ['7', 'property', 1, null],
      ['7', 'payElEntrySum', 2, null],
      ['7', 'payElEntryTime', 3, null],
      ['7', 'payElFundSource', 4, null],
      ['7', 'additionalParams', 5, null],

      ['8', 'property', 1, null],
      ['8', 'payElEntrySum', 2, null],
      ['8', 'payElEntryTime', 3, null],
      ['8', 'payElFundSource', 4, null],
      ['8', 'additionalParams', 5, null],

      ['9', 'payElEntrySum', 1, null],
      ['9', 'payElEntryTime', 2, null],
      ['9', 'payElFundSource', 3, null],
      ['9', 'additionalParams', 4, null],

      ['10', 'property', 1, null],
      ['10', 'payElEntrySum', 2, null],
      ['10', 'payElEntryTime', 3, null],
      ['10', 'payElFundSource', 4, null],
      ['10', 'additionalParams', 5, null],

      ['11', 'property', 1, null],
      ['11', 'payElEntrySum', 2, null],
      ['11', 'payElTimeCost', 3, null],
      ['11', 'payElFundSource', 4, null],
      ['11', 'additionalParams', 5, null],

      ['12', 'property', 1, null],
      ['12', 'payElEntrySum', 2, null],
      ['12', 'payElFundSource', 3, null],
      ['12', 'additionalParams', 4, null],

      ['13', 'property', 1, null],
      ['13', 'payElEntrySum', 2, null],
      ['13', 'payElEntryPlanSum', 3, null],
      ['13', 'payElTimeCostOut', 4, null],
      ['13', 'payElFundSource', 5, null],
      ['13', 'payElTimeExcludePremium', 6, null],
      ['13', 'additionalParams', 7, null],

      ['14', 'property', 1, null],
      ['14', 'additionalParams', 2, null],

      ['15', 'property', 1, null],
      ['15', 'additionalParams', 2, null],

      ['16', 'property', 1, null],
      ['16', 'payElEntrySum', 2, null],
      ['16', 'payElEntryPlanSum', 3, null],
      ['16', 'payElTimeCostOut', 4, null],
      ['16', 'payElFundSource', 5, null],
      ['16', 'payElTimeExcludePremium', 6, null],
      ['16', 'additionalParams', 7, null],

      ['17', 'property', 1, null],
      ['17', 'payElEntryPlanSum', 2, null],
      ['17', 'payElEntrySum', 3, null],
      ['17', 'payElTimeCostOut', 4, null],
      ['17', 'payElExperience', 5, null],
      ['17', 'payElFundSource', 6, null],
      ['17', 'additionalParams', 7, null],

      ['18', 'property', 1, null],
      ['18', 'payElEntryPlanSum', 2, null],
      ['18', 'payElEntrySum', 3, null],
      ['18', 'payElTimeCostOut', 4, null],
      ['18', 'payElExperience', 5, null],
      ['18', 'payElFundSource', 6, null],
      ['18', 'additionalParams', 7, null],

      ['19', 'property', 1, null],
      ['19', 'payElEntryPlanSum', 2, null],
      ['19', 'payElEntrySum', 3, null],
      ['19', 'payElTimeCostOut', 4, null],
      ['19', 'payElExperience', 5, null],
      ['19', 'payElFundSource', 6, null],
      ['19', 'additionalParams', 7, null],

      ['20', 'property', 1, null],
      ['20', 'payElEntryPlanSum', 2, null],
      ['20', 'payElEntrySum', 3, null],
      ['20', 'payElTimeCostOut', 4, null],
      ['20', 'payElExperience', 5, null],
      ['20', 'payElFundSource', 6, null],
      ['20', 'additionalParams', 7, null],

      ['21', 'property', 1, null],
      ['21', 'payElEntrySum', 2, null],
      ['21', 'payElEntryPlanSum', 3, null],
      ['21', 'payElTimeCostOut', 4, null],
      ['21', 'payElFundSource', 5, null],
      ['21', 'payElTimeExcludePremium', 6, null],
      ['21', 'additionalParams', 7, null],

      ['22', 'property', 1, null],
      ['22', 'payElEntrySum', 2, null],
      ['22', 'payElEntryPlanSum', 3, null],
      ['22', 'payElFundSource', 4, null],
      ['22', 'payElTimeExcludePremium', 5, null],
      ['22', 'additionalParams', 6, null],

      ['23', 'property', 1, null],
      ['23', 'payElEntrySum', 2, null],
      ['23', 'payElEntryPlanSum', 3, null],
      ['23', 'payElTimeCostOut', 4, null],
      ['23', 'payElFundSource', 5, null],
      ['23', 'payElTimeExcludePremium', 6, null],
      ['23', 'additionalParams', 7, null],

      ['24', 'property', 1, null],
      ['24', 'payElEntrySum', 2, null],
      ['24', 'payElEntryTime', 3, null],
      ['24', 'payElFundSource', 4, null],
      ['24', 'additionalParams', 5, null],

      ['25', 'property', 1, null],
      ['25', 'payElEntrySum', 2, null],
      ['25', 'payElEntryTime', 3, null],
      ['25', 'payElFundSource', 4, null],
      ['25', 'additionalParams', 5, null],

      ['26', 'property', 1, null],
      ['26', 'payElTaxIndivid', 2, null],
      ['26', 'payElFundSource', 3, null],
      ['26', 'additionalParams', 4, null],

      ['27', 'property', 1, null],
      ['27', 'payElEntrySum', 2, null],
      ['27', 'payElRate', 3, null],
      ['27', 'payElFundSource', 4, null],
      ['27', 'additionalParams', 5, null],

      ['28', 'property', 1, null],
      ['28', 'payElFundSource', 2, null],
      ['28', 'additionalParams', 3, null],

      ['29', 'property', 1, null],
      ['29', 'workPlaces', 2, null],
      ['29', 'payElEntrySum', 3, null],
      ['29', 'payElEntryMinSum', 4, null],
      ['29', 'payElTimeCost', 5, null],
      ['29', 'payElFundSource', 6, null],
      ['29', 'payElAddRetention', 8, null],
      ['29', 'additionalParams', 7, null],

      ['30', 'property', 1, null],
      ['30', 'payElFundSource', 2, null],
      ['30', 'payElAddRetention', 3, null],
      ['30', 'additionalParams', 4, null],

      ['31', 'property', 1, null],
      ['31', 'payElEntrySum', 2, null],
      ['31', 'payElEntryMinSum', 3, '1'],
      ['31', 'payElAlimonyLimit', 4, null],
      ['31', 'payElFundSource', 5, null],
      ['31', 'additionalParams', 6, null],

      ['32', 'property', 1, null],
      ['32', 'payElEntrySum', 2, null],
      ['32', 'payElRate', 3, null],
      ['32', 'payElFundSource', 4, null],
      ['32', 'additionalParams', 5, null],

      ['33', 'property', 1, null],
      ['33', 'payElEntrySum', 2, null],
      ['33', 'payElEntryTime', 3, null],
      ['33', 'payElFundSource', 4, null],
      ['33', 'additionalParams', 5, null],

      ['36', 'property', 1, null],
      ['36', 'payElEntrySum', 2, null],
      ['36', 'payElEntryPlanSum', 3, null],
      ['36', 'payElTimeCostOut', 4, null],
      ['36', 'payElExperience', 5, null],
      ['36', 'payElFundSource', 6, null],
      ['36', 'additionalParams', 7, null],

      ['37', 'property', 1, null],
      ['37', 'payElEntrySum', 2, null],
      ['37', 'payElEntryPlanSum', 3, null],
      ['37', 'payElTimeCostOut', 4, null],
      ['37', 'payElExperience', 5, null],
      ['37', 'payElFundSource', 6, null],
      ['37', 'payElTimeExcludePremium', 7, null],
      ['37', 'additionalParams', 8, null],

      ['38', 'payElFundSource', 3, null],
      ['38', 'additionalParams', 1, null],

      ['40', 'property', 1, null],
      ['40', 'payElEntryPlanSum', 2, null],
      ['40', 'payElEntrySum', 3, null],
      ['40', 'payElTimeCostOut', 4, null],
      ['40', 'payElExperience', 5, null],
      ['40', 'payElFundSource', 6, null],
      ['40', 'additionalParams', 7, null],

      ['41', 'property', 1, null],

      ['42', 'property', 1, null],
      ['42', 'payElFundSource', 2, null],
      ['42', 'additionalParams', 3, null],

      ['43', 'property', 1, null],
      ['43', 'payElFundSource', 2, null],
      ['43', 'additionalParams', 3, null],

      ['44', 'property', 1, null],
      ['44', 'payElEntrySum', 2, null],
      ['44', 'payElEntryPlanSum', 3, null],
      ['44', 'payElTimeCostOut', 4, null],
      ['44', 'payElFundSource', 5, null],
      ['44', 'payElTimeExcludePremium', 6, null],
      ['44', 'additionalParams', 7, null],

      ['45', 'property', 1, null],
      ['45', 'payElEntrySum', 2, null],
      ['45', 'payElFundSource', 3, null],
      ['45', 'additionalParams', 5, null],

      ['46', 'property', 1, null],
      ['46', 'payElEntrySum', 2, null],
      ['46', 'payElExperience', 3, null],
      ['46', 'payElFundSource', 4, null],
      ['46', 'additionalParams', 5, null],

      ['47', 'property', 1, null],
      ['47', 'payElEntrySum', 2, null],
      ['47', 'payElFundSource', 3, null],
      ['47', 'additionalParams', 4, null],

      ['48', 'property', 1, null],
      ['48', 'payElEntrySum', 2, null],
      ['48', 'payElTimeCostOut', 3, null],
      ['48', 'payElExperience', 4, null],
      ['48', 'payElFundSource', 5, null],
      ['48', 'additionalParams', 6, null],

      ['49', 'property', 1, null],
      ['49', 'payElEntrySum', 2, null],
      ['49', 'payElTimeCostNot', 3, null],
      ['49', 'payElFundSource', 4, null],
      ['49', 'additionalParams', 5, null],

      ['50', 'property', 1, null],
      ['50', 'payElEntrySum', 2, null],
      ['50', 'payElTimeCostOut', 3, null],
      ['50', 'payElFundSource', 4, null],
      ['50', 'additionalParams', 5, null],

      ['51', 'property', 1, null],
      ['51', 'payElEntrySum', 2, null],
      ['51', 'payElTimeCostOut', 3, null],
      ['51', 'payElFundSource', 4, null],
      ['51', 'additionalParams', 5, null],

      ['53', 'payElFundSource', 1, null],
      ['53', 'additionalParams', 2, null],

      ['56', 'property', 1, null],
      ['56', 'payElEntrySum', 2, null],
      ['56', 'payElEntryTime', 3, null],
      ['56', 'payElFundSource', 4, null],
      ['56', 'additionalParams', 5, null],

      ['57', 'property', 1, null],
      ['57', 'payElFundSource', 2, null],
      ['57', 'additionalParams', 3, null],

      ['58', 'property', 1, null],
      ['58', 'payElEntrySum', 2, null],
      ['58', 'payElTimeCostOut', 3, null],
      ['58', 'payElFundSource', 4, null],
      ['58', 'payElTimeExcludePremium', 5, null],
      ['58', 'additionalParams', 6, null],

      ['61', 'property', 1, null],
      ['61', 'payElEntrySum', 2, null],
      ['61', 'payElEntryMinSum', 3, '1'],
      ['61', 'payElFundSource', 4, null],
      ['61', 'additionalParams', 5, null],

      ['62', 'property', 1, null],
      ['62', 'payElEntrySum', 2, null],
      ['62', 'payElFundSource', 3, null],
      ['62', 'additionalParams', 4, null],

      ['63', 'property', 1, null],
      ['63', 'payElTimeCost', 2, null],
      ['63', 'additionalParams', 3, null],

      ['65', 'property', 1, null],
      ['65', 'payElEntrySum', 2, null],
      ['65', 'payElFundSource', 3, null],
      ['65', 'additionalParams', 4, null],

      ['67', 'property', 1, null],
      ['67', 'payElEntrySum', 2, null],
      ['67', 'payElEntryPlanSum', 3, null],
      ['67', 'payElTimeCostOut', 4, null],
      ['67', 'payElFundSource', 5, null],
      ['67', 'payElTimeExcludePremium', 6, null],
      ['67', 'additionalParams', 7, null],

      ['68', 'property', 1, null],
      ['68', 'payElEntrySum', 2, null],
      ['68', 'payElFundSource', 3, null],
      ['68', 'additionalParams', 4, null],

      ['71', 'property', 1, null],
      ['71', 'payElEntrySum', 2, null],
      ['71', 'payElEntryPlanSum', 3, null],
      ['71', 'payElTimeCostOut', 4, null],
      ['71', 'payElFundSource', 5, null],
      ['71', 'payElTimeExcludePremium', 6, null],
      ['71', 'additionalParams', 7, null],

      ['72', 'payElFundSource', 1, null],
      ['72', 'property', 2, null],

      ['73', 'property', 1, null],
      ['73', 'payElEntrySum', 2, null],
      ['73', 'payElEntryPlanSum', 3, null],
      ['73', 'payElTimeCostOut', 4, null],
      ['73', 'payElFundSource', 5, null],
      ['73', 'payElTimeExcludePremium', 6, null],
      ['73', 'additionalParams', 7, null],

      ['74', 'property', 1, null],
      ['74', 'payElEntrySum', 2, null],
      ['74', 'payElFundSource', 3, null],
      ['74', 'additionalParams', 4, null],

      ['75', 'property', 1, null],
      ['75', 'payElFundSource', 3, null],
      ['75', 'additionalParams', 1, null],

      ['77', 'property', 1, null],
      ['77', 'payElTimeCost', 2, null],
      ['77', 'payElFundSource', 3, null],
      ['77', 'additionalParams', 4, null],

      ['134', 'property', 1, null],

      ['135', 'payElFundSource', 1, null],
      ['135', 'additionalParams', 2, null],

      ['137', 'property', 1, null],
      ['137', 'payElEntrySum', 2, null],
      ['137', 'payElTimeCost', 3, null],
      ['137', 'payElFundSource', 4, null],
      ['137', 'additionalParams', 5, null],

      ['138', 'property', 1, null],
      ['138', 'payElTimeCost', 1, null],
      ['138', 'payElFundSource', 2, null],
      ['138', 'additionalParams', 3, null],

      ['140', 'property', 1, null],
      ['140', 'payElFundSource', 2, null],
      ['140', 'additionalParams', 3, null],

      ['141', 'property', 1, null],
      ['141', 'payElFundSource', 1, null],
      ['141', 'additionalParams', 2, null],

      ['142', 'property', 1, null],
      ['142', 'payElEntrySum', 2, null],
      ['142', 'payElEntryPlanSum', 3, null],
      ['142', 'payElTimeCostOut', 4, null],
      ['142', 'payElFundSource', 5, null],
      ['142', 'payElTimeExcludePremium', 6, null],
      ['142', 'additionalParams', 7, null],

      ['144', 'property', 1, null],
      ['144', 'payElEntrySum', 2, null],

      ['146', 'property', 1, null],
      ['146', 'payElTimeCost', 1, null],
      ['146', 'payElFundSource', 2, null],
      ['146', 'additionalParams', 3, null],

      ['147', 'property', 1, null],
      ['147', 'payElTimeCost', 2, null],
      ['147', 'payElFundSource', 3, null],
      ['147', 'additionalParams', 4, null],

      ['148', 'payElEntrySum', 1, null],
      ['148', 'payElEntryTime', 2, null],
      ['148', 'payElFundSource', 3, null],
      ['148', 'additionalParams', 4, null],

      ['149', 'property', 1, null],
      ['149', 'payElEntrySum', 2, null],
      ['149', 'payElTimeCostOut', 3, null],
      ['149', 'payElExperience', 4, null],
      ['149', 'payElFundSource', 5, null],
      ['149', 'additionalParams', 6, null],

      ['150', 'payElFundSource', 1, null],
      ['150', 'additionalParams', 2, null],

      ['151', 'property', 1, null],
      ['151', 'payElFundSource', 2, null],
      ['151', 'additionalParams', 3, null],

      ['152', 'property', 1, null],

      ['153', 'property', 1, null],
      ['153', 'payElEntrySum', 2, null],
      ['153', 'payElEntryTime', 3, null],
      ['153', 'payElFundSource', 4, null],
      ['153', 'additionalParams', 5, null],

      ['154', 'payElEntrySum', 1, null],
      ['154', 'payElEntryTime', 2, null],
      ['154', 'payElFundSource', 3, null],
      ['154', 'additionalParams', 4, null],

      ['155', 'payElEntrySum', 1, null],
      ['155', 'payElEntryTime', 2, null],
      ['155', 'payElFundSource', 3, null],
      ['155', 'additionalParams', 4, null],

      ['156', 'property', 1, null],
      ['156', 'payElTimeCost', 2, null],
      ['156', 'payElFundSource', 3, null],
      ['156', 'additionalParams', 4, null],

      ['159', 'property', 1, null],
      ['159', 'payElTimeCost', 2, null],
      ['159', 'payElFundSource', 3, null],
      ['159', 'additionalParams', 4, null],

      ['201', 'property', 1, null],
      ['201', 'payElEntrySum', 2, null],
      ['201', 'payElEntryPlanSum', 3, null],
      ['201', 'payElTimeCostOut', 4, null],
      ['201', 'payElTimeCostNot', 5, null],
      ['201', 'payElTimeExcludePremium', 6, null],
      ['201', 'payElFundSource', 7, null],
      ['201', 'additionalParams', 8, null],

      ['202', 'property', 1, null],
      ['202', 'payElEntrySum', 2, null],
      ['202', 'payElFundSource', 5, null],
      ['202', 'additionalParams', 6, null],

      ['203', 'property', 1, null],
      ['203', 'payElEntrySum', 2, null],
      ['203', 'payElEntryPlanSum', 3, null],
      ['203', 'payElTimeCostOut', 4, null],
      ['203', 'payElTimeExcludePremium', 5, null],
      ['203', 'payElAccrualReserve', 6, null],
      ['203', 'payElUseReserve', 7, null],
      ['203', 'additionalParams', 8, null],

      ['204', 'property', 1, null],
      ['204', 'payElTimeCost', 2, null],
      ['204', 'payElEntrySum', 3, '2'],
      ['204', 'payElAddRetention', 4, '3'],
      ['204', 'payElFundSource', 5, null],
      ['204', 'additionalParams', 6, null],

      ['205', 'property', 1, null],
      ['205', 'payElTimeCost', 2, null],
      ['205', 'payElEntrySum', 3, '2'],
      ['205', 'payElAddRetention', 4, '3'],
      ['205', 'payElFundSource', 5, null],
      ['205', 'additionalParams', 6, null],

      ['206', 'property', 1, null],
      ['206', 'payElEntrySum', 2, '2'],
      ['206', 'payElAddRetention', 3, '3'],
      ['206', 'payElTimeCostNot', 4, null],
      ['206', 'payElFundSource', 5, null],
      ['206', 'additionalParams', 6, null],

      ['207', 'property', 1, null],
      ['207', 'payElEntrySum', 2, null],
      ['207', 'payElEntryTime', 3, null],
      ['207', 'payElFundSource', 4, null],
      ['207', 'additionalParams', 5, null],

      ['208', 'property', 1, null],
      ['208', 'payElFundSource', 2, null],
      ['208', 'additionalParams', 3, null]

    ]
  }
]
