module.exports = [
  {
    entity: 'hr_empOrderDetConfigAttr',
    identifier: ['empOrderType', 'attrName'],
    notUpdate: true,
    notDelete: true,
    modifyWhere: (conn) => {
      return !conn.Repository('hr_empOrderDetConfigAttr').attrs(['ID']).misc({ __allowSelectSafeDeleted: true }).limit(1).selectScalar()
    },
    attrs: ['empOrderType', 'attrName'],
    items: [
      ['ACTING', 'payElIDReplacement'],
      ['ACTINGORD', 'payElIDReplacement'],
      ['BOUNTY', 'payElIDMain'],
      ['BOUNTY_HELP', 'payElIDMain'],
      ['DISM', 'payElIDAccrual'],
      ['DISM', 'payElIDMain'],
      ['DISM', 'payElIDAdd'],
      ['VACATION', 'payElIDAdd'],
      ['VACATION', 'payElIDReplacement'],
      ['VACATION_G', 'payElIDAdd'],
      ['VACATION_G', 'payElIDReplacement'],
      ['VACATIONLONG', 'payElIDReplacement'],
      ['VACATIONLONG_G', 'payElIDReplacement'],
      ['VACATIONCOMP', 'payElIDMain'],
      ['TRAINING', 'dictTimeCostID'],
      ['TRAINING', 'payElIDMain'],
      ['TRAINING', 'payElIDReplacement'],
      ['RANK', 'payElIDMain'],
      ['MISSION', 'dictTimeCostID'],
      ['MISSION', 'payElIDMain'],
      ['MISSION', 'payElIDReplacement'],
      ['MISSION_G', 'dictTimeCostID'],
      ['MISSION_G', 'payElIDMain'],
      ['MISSION_G', 'payElIDReplacement'],
      ['MISSION_TRAINING', 'dictTimeCostID'],
      ['MISSION_TRAINING', 'payElIDMain'],
      ['MISSION_TRAINING', 'payElIDReplacement'],
      ['CWSRELAXHD', 'dictTimeCostID'],
      ['CWSRELAXHD', 'payElIDMain'],
      ['CWSRELAXDONOR', 'dictTimeCostID'],
      ['CWSRELAXDONOR', 'payElIDMain'],
      ['MILSERVICE', 'dictTimeCostID'],
      ['MILSERVICE', 'payElIDMain'],
      ['DOWNTIME', 'payElIDMain'],
      ['RISKPAY', 'payElIDMain'],
      ['APPOINT_HOUR', 'payElIDAccrual'],
      ['CWSHD', 'dictTimeCostID'],
      ['CWSHD', 'dictTimeCost2ID'],
      ['CWSHD_PAY', 'dictTimeCostID'],
      ['CWSHD_VAC', 'dictTimeCostID'],
      ['CWSHD_VAC', 'dictTimeCost2ID'],
      ['MOVE', 'payElIDMain']
    ]
  }
]
